### ISSUE TITLE
Unable to mount two folders on same EFS volume

### ISSUE THREAD

**Issue by stefansedich** [kubernetes-sigs/aws-efs-csi-driver#100]
/kind bug

**What happened?**

When attempting to mount two different folders on the same EFS volume using multiple PV and PVCs the pod fails to start showing a timeout binding the volumes:

```
Unable to mount volumes for pod "efs_default": timeout expired waiting for volumes to attach or mount for pod "default"/"efs". list of unmounted volumes=[efs-test2]. list of unattached volumes=[efs-test efs-test2 default-token-nffl4]
```

Binding works fine if I mount only one of the volumes, doesn't matter which one but as soon as there is >1 it fails.

**What you expected to happen?**

I would expect this to work as it did when I was previously using an NFS PV.

**How to reproduce it (as minimally and precisely as possible)?**

Use the following manifests, it will require an EFS volume with the `/efs-test` and `/efs-test2` folders created.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-test
spec:
  storageClassName: efs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxx
    volumeAttributes:
      path: "/efs-test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs
  volumeName: efs-test
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-test2
spec:
  storageClassName: efs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxx
    volumeAttributes:
      path: "/efs-test2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-test2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs
  volumeName: efs-test2
---
apiVersion: v1
kind: Pod
metadata:
  name: efs
spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: /mnt/efs-test
          name: efs-test
          readOnly: false
        - mountPath: /mnt/efs-test2
          name: efs-test2
          readOnly: false
  volumes:
    - name: efs-test
      persistentVolumeClaim:
        claimName: efs-test
    - name: efs-test2
      persistentVolumeClaim:
        claimName: efs-test2
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1,14
- Driver version: 0.2.0

**Comment by ShanHsl** [comment]
我也有同样的问题，我做了测试。发现问题在一个pod无法挂载多个pvc。

**Comment by ShanHsl** [comment]
以下为我做测试的yaml和结果
不可以执行的yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: volume-debugger
spec:
  volumes:
    - name: airflow-dags
      persistentVolumeClaim:
       claimName: airflow-dags
    - name: airflow-logs
      persistentVolumeClaim:
       claimName: airflow-logs
  containers:
    - name: debugger
      image: debug:1.10.5
      command: ['sleep', '36000']
      volumeMounts:
        - name: airflow-dags
          mountPath: /root/airflow/dags
        - name: airflow-logs
          mountPath: /root/airflow/logs
```
报错信息如下：
  Warning  FailedMount  112s (x3 over 6m23s)  kubelet, ip-xxxx-xxxx-xxxx-xxxx.ec2.internal  Unable to mount volumes for pod "volume-debugger_airflow(8e802dfa-fbef-11e9-99a0-0eea81d2edb2)": timeout expired waiting for volumes to attach or mount for pod "airflow"/"volume-debugger". list of unmounted volumes=[airflow-logs]. list of unattached volumes=[airflow-dags airflow-logs default-token-xt7gr]

**Comment by ShanHsl** [comment]
pv和pvc：
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-dags
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: f s
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-**********
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-**********
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
```

**Comment by leakingtapan** [comment]
I did some quick testing and able to reproduce the same. Taking a look

**Comment by leakingtapan** [comment]
There wasn't even call into the driver for `NodePublishVolume` on pv2:

```
I1107 19:43:50.153495       1 node.go:49] NodePublishVolume: called with args volume_id:"fs-8bbb3e0a" target_path:"/var/lib/kubelet/pods/cf02d596-adcd-498d-b9a7-aba672b288ef/volumes/kubernetes.io~csi/efs-pv2/mount" volume_capability:<mount:<> access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:"path" value:"/test2" >
I1107 19:43:50.153556       1 node.go:103] NodePublishVolume: creating dir /var/lib/kubelet/pods/cf02d596-adcd-498d-b9a7-aba672b288ef/volumes/kubernetes.io~csi/efs-pv2/mount
I1107 19:43:50.153575       1 node.go:108] NodePublishVolume: mounting fs-8bbb3e0a:/test2 at /var/lib/kubelet/pods/cf02d596-adcd-498d-b9a7-aba672b288ef/volumes/kubernetes.io~csi/efs-pv2/mount with options []
I1107 19:43:50.153586       1 mount_linux.go:135] Mounting cmd (mount) with arguments ([-t efs fs-8bbb3e0a:/test2 /var/lib/kubelet/pods/cf02d596-adcd-498d-b9a7-aba672b288ef/volumes/kubernetes.io~csi/efs-pv2/mount])
```

**Comment by leakingtapan** [comment]
Tested consume two PVs each with different EFS filesystem ID and it works.

```
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-8bbb3e0a
    #volumeAttributes:
    #  path: /test1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-3e63e6bf
    #volumeAttributes:
    #  path: /test2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: pv1
      mountPath: /data/pv1
    - name: pv2
      mountPath: /data/pv2
  volumes:
  - name: pv1
    persistentVolumeClaim:
      claimName: efs-claim1
  - name: pv2
    persistentVolumeClaim:
      claimName: efs-claim2
```

**Comment by leakingtapan** [comment]
I think I figured out why. The cause is because both PVs are using the same filesystem ID as the `volumeHandle`. It makes perfect sense for a RWX volume to reuse the same `volumeHandle` value, since the volume is expected to be shared by multiple containers.

However, kubernetes is handing such case problematically. In the volume manager's desired_state_of_world cache, it figures out whether a volume needs to be mounted by a unique volume name [here](https://github.com/kubernetes/kubernetes/blob/v1.14.8/pkg/kubelet/volumemanager/cache/desired_state_of_world.go#L214). And the csi_plugin 's [`GetVolumeName`](https://github.com/kubernetes/kubernetes/blob/v1.14.8/pkg/kubelet/volumemanager/cache/desired_state_of_world.go#L214) method determines volume name only by CSI driver name and `volumeHandle`. This causes the second EFS CSI volume never to be mounted (since kubelet will not call CSI driver again)

**Comment by leakingtapan** [comment]
As required by CSI Volume [here](https://kubernetes.io/docs/concepts/storage/volumes/#csi), volume handle needs to unique identify the volume. 

The fix will be modify subpath feature to be specifying the subpath through `volumeHandle` as such:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-3e63e6bf:/test2
```

If I remove the `subpath` field under `volumeAttributes`, this will be a backward incompatible change unfortunately.
