### ISSUE TITLE
EFS on EKS Multiple Namespace  

### ISSUE THREAD

**Issue by SAURABH110894** [kubernetes-sigs/aws-efs-csi-driver#1033]
Pre requisite
  - EFS 
  - EKS Cluster (v1.26)

I have completed EFS Setup on EKS with help of AWS Docs (https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)
Now the problem is I'm not able Provision PVC on Namespace Level. 

Below is My Code. 
This will Create Two Namespace.
```
kubectl create ns dev 
kubectl create ns qa
```

Create SC 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
```

Create PV

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-4af69aab
```

Create PVC for Dev Namespace (Taking 4GB)

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 4Gi
```
Create PVC for QA Namespace (Taking 1GB)

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: qa
  name: efs-claim-qa
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
```
Pod File Dev

```
apiVersion: v1
kind: Pod
metadata:
  namespace: dev 
  name: app1
spec:
  containers:
  - name: app1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim

```
Pod QA File 

```
apiVersion: v1
kind: Pod
metadata:
  namespace: qa
  name: app1
spec:
  containers:
  - name: app1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out2.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim-qa
```
Result :- for Dev Namespace it's working but QA Namespace it's not working. 

PVC for QA is Showing Pending. 

Please help me if i missed something !!!!

This Error :
```
kubectl describe pvc efs-claim-qa -n qa
Name:          efs-claim-qa
Namespace:     qa
StorageClass:  efs-sc
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: efs.csi.aws.com
               volume.kubernetes.io/storage-provisioner: efs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                  From                                                                                            Message
  ----     ------                ----                 ----                                                                                            -------
  Normal   Provisioning          20s (x9 over 2m27s)  efs.csi.aws.com_ip-10-0-0-180.ap-south-1.compute.internal_7cbc9330-a279-4af8-9adc-7562b37c13e5  External provisioner is provisioning volume for claim "qa/efs-claim-qa"
  Warning  ProvisioningFailed    20s (x9 over 2m27s)  efs.csi.aws.com_ip-10-0-0-180.ap-south-1.compute.internal_7cbc9330-a279-4af8-9adc-7562b37c13e5  failed to provision volume with StorageClass "efs-sc": rpc error: code = InvalidArgument desc = Missing provisioningMode parameter
  Normal   ExternalProvisioning  3s (x11 over 2m27s)  persistentvolume-controller                                                                     waiting for a volume to be created, either by external provisioner "efs.csi.aws.com" or manually created by system administrator



```

For Dev Namespace it's working fine.
```
kubectl describe pvc efs-claim-dev -n dev
Name:          efs-claim-dev
Namespace:     dev
StorageClass:  efs-sc
Status:        Bound
Volume:        efs-pv
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       <none>
Events:        <none>
```
Not Sure Why Not working for QA Namespace.
