### ISSUE TITLE
efs csi driver is not being deployed on ec2 node but on fargate profile

### ISSUE THREAD

**Issue by rjtshrm** [kubernetes-sigs/aws-efs-csi-driver#1068]
I have EKS cluster mix of fargate and EC2 node. I want to deploy EFS CSI driver on ec2 nodes as I am getting error on Fargate as HostNetwork is not supported. I have also added the following affinity in the helm values

```
controller:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
```

But still It is getting deployed to fargate profile (can be seen in the labels that it is assigned to profile default). I can also see the affinity in Deployed Pod config that affinity and nodeselector are correct. Any idea how can I deploy it on EC2 nodes.

<img width="811" alt="image" src="https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/6351392/f9882a7b-2c55-4ec5-a5f2-fe7aaeb5728a">
