### ISSUE TITLE
PVC creation failing with failed to create access point due to ValidationException for rootDirectory.path

### ISSUE THREAD

**Issue by mssachan** [kubernetes-sigs/aws-efs-csi-driver#1073]
We are trying to create PVC using following storageclass and PVC spec

**StorageClass Spec**
```
mountOptions:
  - tls
  parameters:
    basePath: /
    directoryPerms: "700"
    fileSystemId: fs-0ea8cf392a323eea7
    gidRangeEnd: "7000000"
    gidRangeStart: "50000"
    provisioningMode: efs-ap
  provisioner: efs.csi.aws.com
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
```

**PVC spec:**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sat-aws-file-test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: efs-test`
  resources:
    requests:
      storage: 10Gi
```

but PVC creation failing with following error
```
Warning  ProvisioningFailed  93s   efs.csi.aws.com_ip-10-21-2-237_a24de5d6-16ea-41b6-bd48-060f499febdb  failed to provision volume with StorageClass "efs-test": rpc error: code = Internal desc = Failed to create Access point in File System fs-0ea8cf392a323eea7 : Failed to create access point: ValidationException: 1 validation error detected: Value '//pvc-652c9d9b-947d-4d6a-8562-087f43c7a46b' at 'rootDirectory.path' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\/|(\/(?!\.)+[^$#<>;`|&?{}^*/\n]+){1,4})$
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "9da55af1-b556-4546-a621-fbff514e0766"
  },
  Message_: "1 validation error detected: Value '//pvc-652c9d9b-947d-4d6a-8562-087f43c7a46b' at 'rootDirectory.path' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\\/|(\\/(?!\\.)+[^$#<>;`|&?{}^*/\\n]+){1,4})$"
}
```

Could you please tell the reason for this failure and how to fix the issue?
FYI, We are using AWS EFS driver 1.4.2 and we have not face this issue before.
