### ISSUE TITLE
helm chart: `node.hostAliases` does not support multiple AZ for the same FS id

### ISSUE THREAD

**Issue by jj-mino** [kubernetes-sigs/aws-efs-csi-driver#1141]
/kind bug

**What happened?**
When we pass below values to the helm chart to support multiple availability zones, only one entry is added, as the others are overwritten by [this](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/v1.6.0/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L28-L33) logic:
```yaml
node:
  hostAliases:
    fs-010101010101010110: 
      ip: "10.6.0.5" # mount target IP for az1
      region: "us-west-2"
    fs-010101010101010110: 
      ip: "10.6.0.6" # mount target IP for az2
      region: "us-west-2"
    fs-010101010101010110: 
      ip: "10.6.0.7" # mount target IP for az3
      region: "us-west-2"
```

**What you expected to happen?**
I would like to set multiple IPs for the same Filesystem ID

**How to reproduce it (as minimally and precisely as possible)?**
1) Deploy the helm chart with above values
2) Review the daemonset configured hostaliases (`kubectl edit daemonset efs-csi-node -n kube-system`)

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 
  - Client Version: v1.28.1
  - Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  - Server Version: v1.27.4-eks-2d98532
- Driver version: aws-efs-csi-driver helm chart `v2.4.9`

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)
