### ISSUE TITLE
Cleanup of resources

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/aws-efs-csi-driver#1150]
/kind bug

**What happened?**
If you create a pvc with dynamic provisioning a pv will be created in k8s and an access point will be created in efs. If you delete the pvc the pv stays there, if you manually delete the pv the acess point will stay there too.

**What you expected to happen?**
- An option to auto delete pv in case pvc is deleted.
- An option to auto delete the access point in case pv is deleted.

**How to reproduce it (as minimally and precisely as possible)?**

`````
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-299dde71
  directoryPerms: "700"
  uid: "82"
  gid: "2000"
  provisioner: efs.csi.aws.com
  #basePath: "/"
  subPathPattern: "/${.PVC.name}"
  ensureUniqueDirectory: "false"
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - mountPath: /tmp
      name: efs
      readOnly: false
  restartPolicy: Always
  volumes:
    - name: efs
      persistentVolumeClaim:
        claimName: wp-bedrock-sample
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-bedrock-sample
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi
`````

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.27.4
- Driver version: 1.7.0

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)
