### ISSUE TITLE
Established NFS connections hang after network connectivity interrupted

### ISSUE THREAD

**Issue by otakumike** [kubernetes-sigs/aws-efs-csi-driver#117]
/kind bug

**What happened?**
One of our nodes had a very brief failure in which Calico seemed to restart. We're not sure of the root cause here, but momentarily Calico was lost to us and then healed itself: 

```
calico-node	2019-12-31 03:28:30.652 [WARNING][55] health.go 190: Reporter failed readiness checks name="int_dataplane" reporter-state=&health.reporterState{name:"int_dataplane", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:true}, timestamp:time.Time{wall:0xbf7acdf1ac9ae5a5, ext:186458634869, loc:(*time.Location)(0x2b29100)}}
calico-node	2019-12-31 03:28:30.652 [WARNING][55] health.go 184: Reporter failed liveness checks name="int_dataplane" reporter-state=&health.reporterState{name:"int_dataplane", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:true}, timestamp:time.Time{wall:0xbf7acdf1ac9ae5a5, ext:186458634869, loc:(*time.Location)(0x2b29100)}}
calico-node	2019-12-31 03:28:30.652 [INFO][55] health.go 178: Overall health status changed lastSummary=&health.HealthReport{Live:false, Ready:false}
```

After Calico failed, the EFS CSI daemonset running on this node reported an issue connecting to the unix socket: 

```
E1231 03:28:41.720414       1 connection.go:129] Lost connection to unix:///csi/csi.sock.
```

Even though Calico came back up a few seconds later and the node went on working like normal, all established EFS connections hung. On the host, things like `df` never completed running and the containers that were using these EFS mounts would fail to terminate. 

**What you expected to happen?**
When the EFS CSI driver loses connections to the Unix socket, it should try to recover lost NFS connections or destroy them, forcing pods to be rescheduled.

**How to reproduce it (as minimally and precisely as possible)?**
Interrupt network connectivity on a node briefly, then re-connect. However, I have not tested this.  

**Anything else we need to know?**:
I was able to recover from this issue by forcefully 'umount'ing the hanging NFS connections on the host. Nothing needed to be done to get new NFS connections running on the host, it was only those connections that were active when the socket failed which were broken. 

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
v0.2.0

Thank you!

**Comment by jqmichael** [comment]
@otakumike Do you mind showing us your PV spec? Want to check if you enabled TLS.

**Comment by otakumike** [comment]
sure, here's a slightly redacted example:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: <snip>
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2019-12-04T01:22:52Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: efs-<customer>-prod
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: efs-<customer>-prod
    namespace: <snip>
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-XXXXXXXX
  mountOptions:
  - noexec
  - nodev
  - tls
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  volumeMode: Filesystem
status:
  phase: Bound
```
