### ISSUE TITLE
Shorten UID appended to subPathPattern

### ISSUE THREAD

**Issue by micolun** [kubernetes-sigs/aws-efs-csi-driver#1187]
**Is your feature request related to a problem? /Why is this needed**
AWS EFS access points have a limit of 100 characters for the full path, as described here 
https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html#enforce-root-directory-access-point 

The unique ID suffixed to subPathPattern has (if I am not mistaken) 38 characters, including hyphens.
This greatly limits the subPathPattern length,  where only 5 alphanumeric characters would suffice.

/feature

**Describe the solution you'd like in detail**
Limit suffixed UID to 5 characters, same length as kubernetes appends to the pods, after replicaSets name.

**Describe alternatives you've considered**
If [subPathPattern]+[PVC_name] are less than 100 characters, limit the UID length so the full path is no longer than 100.

**Additional context**
Here is result of me deploying prometheus alertmanager with helm , and it trying to provision a dynamic volume.
storage Class parameters
```yaml
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: '0755'
  ensureUniqueDirectory: 'true'
  fileSystemId: fs-0619b4a92a3452b2d
  gid: '10000'
  provisioningMode: efs-ap
  subPathPattern: ${.PVC.namespace}/${.PVC.name}
  uid: '10000'
```
Error message
```
E1109 17:15:47.167463       1 controller.go:957] error syncing claim "58f24f0c-c6a4-4f28-a9c4-be61c0365b55": failed to provision volume with StorageClass "mcv-lon-demo-1-efs-monitoring-data": rpc error: code = InvalidArgument desc = Proposed path '/dynamic_provisioning/monitoring/storage-prometheus-alertmanager-0-10da02e7-9ae5-4108-8144-0b4b34fa1bc4' exceeds EFS limit of 100 characters
I1109 17:15:47.167853       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"monitoring", Name:"storage-prometheus-alertmanager-0", UID:"58f24f0c-c6a4-4f28-a9c4-be61c0365b55", APIVersion:"v1", ResourceVersion:"121958", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "mcv-lon-demo-1-efs-monitoring-data": rpc error: code = InvalidArgument desc = Proposed path '/dynamic_provisioning/monitoring/storage-prometheus-alertmanager-0-10da02e7-9ae5-4108-8144-0b4b34fa1bc4' exceeds EFS limit of 100 characters
```
