### ISSUE TITLE
efs.csi.aws.com/agent-not-ready:NoExecute taint not being removed

### ISSUE THREAD

**Issue by zackery-parkhurst** [kubernetes-sigs/aws-efs-csi-driver#1236]
/kind bug

**What happened?**
I have been running the efs csi driver successfully for a few months now. And everything appears to be working as expected. My EFS filesystem is successfully mounted into my pods and the apps can use the files in the mounted EFS. 

However, I was reading the [documentation](https://github.com/kubernetes-sigs/aws-efs-csi-driver?tab=readme-ov-file#configure-node-startup-taint) and noticed that there is a startup taint that we can use to avoid a race condition that sometimes happens. And that the EFS Driver is supposed remove the taint once driver becomes ready. And it is stated that this feature is turned on by default. 

So I tried doing this, and tainted my k8s node as instructed in [documentation](https://github.com/kubernetes-sigs/aws-efs-csi-driver?tab=readme-ov-file#configure-node-startup-taint).
However, the taint was never removed. Even though the efs-csi-node pods were up and ready.  Causing my workload pods to never be able to be scheduled onto the node. Even though the efs-csi-node pod is up and running. 

**What you expected to happen?**
I expected the taint to be removed as described on the main README.md page [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver?tab=readme-ov-file#configure-node-startup-taint)

**How to reproduce it (as minimally and precisely as possible)?**
Add the specified taint, `efs.csi.aws.com/agent-not-ready:NoExecute`, as a startup taint. 
Watch the efs-csi-node daemonset pod start and become ready and examine that the startup taint will never be removed. 

I installed the EFS-CSI Driver via terraform + helm. 
Here is the code for that: 
```
resource "helm_release" "efs_csi" {
  name       = "aws-efs-csi-driver"
  namespace  = var.circle_namespace
  repository = "https://kubernetes-sigs.github.io/aws-efs-csi-driver/"
  chart      = "aws-efs-csi-driver"

  values = [
    templatefile("${path.module}/efs.tpl", {})
  ]
}
```

And the values file for helm chart (efs.tpl): 
```
replicaCount: 1

controller:
  logLevel: 5
  serviceAccount:
    create: false
    name: efs-csi-sa
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

node:
  logLevel: 5
  serviceAccount:
    create: false
    name: efs-csi-sa
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

**Anything else we need to know?**:

**Environment**
- Driver version: Helm Chart - 2.5.1, App Version - 1.7.1
- Kubernetes version - 1.27
- Node kubelet version - v1.27.7-eks-e71965b
- Node Kernel Version - 5.10.201-191.748.amzn2.x86_64
- Node OS / Image - linux(amd64) / Amazon Linux 2

**Please also attach debug logs to help us better diagnose**

I have included both debug logs from the efs-csi-node pod and the efs-csi-controller pod. Which both are in dubug mode or logLevel=5
[efs-csi-controller-58d458977f-cwn6h.log](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13833675/efs-csi-controller-58d458977f-cwn6h.log)
[efs-csi-node-pdzg2.log](https://github.com/kubernetes-sigs/aws-efs-csi-driver/files/13833676/efs-csi-node-pdzg2.log)

![image](https://github.com/kubernetes-sigs/aws-efs-csi-driver/assets/97055114/125afa68-d08c-439e-9833-b18de2ad08b1)
