### ISSUE TITLE
securityContext doesn't applied when creating pvc

### ISSUE THREAD

**Issue by Amos-85** [kubernetes-sigs/aws-efs-csi-driver#125]
/kind bug

**What happened?**
Deploy Hashicorp [vault helm chart ](https://github.com/hashicorp/vault-helm) that include this `securityContext` below without the specified uid/gid ( the /vault/data folder created by root ):
```
securityContext:
        runAsNonRoot: true
        runAsGroup: {{ .Values.server.gid | default 1000 }}
        runAsUser: {{ .Values.server.uid | default 100 }}
        fsGroup: {{ .Values.server.gid | default 1000 }}
```

**What you expected to happen?**
mount efs persistent volume with the right `securityContext` attributes
**How to reproduce it (as minimally and precisely as possible)?**
deploy vault helm chart with declaring the right storageClass that represents efs.

**Environment**
- `Kubernetes version: v1.15.3`
- `Driver version: 0.2.0`
