### ISSUE TITLE
Volume mounts time out after upgrading aws-efs-csi-driver from 1.7.7 to 2.0.2

### ISSUE THREAD

**Issue by MiGrandjean** [kubernetes-sigs/aws-efs-csi-driver#1343]
/kind bug

**What happened?**

After upgrading the Helm Chart from `v2.5.7` to `v3.0.3` (which also updates the aws-efs-csi-driver from `v1.7.7` to `v2.0.2`), new volume mounts of our Pods time out and then fail:

```
E0503 08:47:46.370467       1 driver.go:106] GRPC error: rpc error: code = Internal desc = Could not mount "fs-00bbbbbbbbbbbbbbb:/" at "/var/lib/kubelet/pods/88a4322e-686d-4eae-a045-77edd4f4e07b/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673948/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o accesspoint=fsap-02d4502d4502d4502,tls fs-00bbbbbbbbbbbbbbb:/ /var/lib/kubelet/pods/88a4322e-686d-4eae-a045-77edd4f4e07b/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673948/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
Mount attempt 1/3 failed due to timeout after 15 sec, wait 0 sec before next attempt.
Mount attempt 2/3 failed due to timeout after 15 sec, wait 0 sec before next attempt.
b'mount.nfs4: Connection timed out'
```

**What you expected to happen?**

Successfully mount the volume :)

**How to reproduce it (as minimally and precisely as possible)?**

- Upgrade the Helm Chart from v2.5.7 to v3.0.3 with the following Helm Values:

```yaml
controller:
  deleteAccessPointRootDir: false
  logLevel: 5
  serviceAccount:
    create: true
    name: efs-csi-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/AmazonEKS_EFS_CSI_DriverRole
node:
  logLevel: 5
  volMetricsOptIn: false
  serviceAccount:
    create: true
    name: efs-csi-node-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/AmazonEKS_EFS_CSI_DriverRole
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
storageClasses:
- mountOptions:
  - tls
  name: efs-sc-tools
  parameters:
    directoryPerms: "700"
    fileSystemId: fs-99999999999999999
    provisioningMode: efs-ap
- mountOptions:
  - tls
  name: efs-sc-apps
  parameters:
    directoryPerms: "700"
    fileSystemId: fs-00bbbbbbbbbbbbbbb
    gid: "999"
    provisioningMode: efs-ap
    uid: "999"
```

**Anything else we need to know?**:

- The role `AmazonEKS_EFS_CSI_DriverRole` has the AWS managed `AmazonEFSCSIDriverPolicy` policy attached and was created according to https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/docs/iam-policy-create.md
- The EFS Filesystem (fs-00bbbbbbbbbbbbbbb) has a Security Group attached to the Network Access, that allows a) Inbound TCP on Port 2049 from the VPC CIDR and b) all Outbound traffic
- The moment I downgrade the Helm Chart to v2.5.7 (aws-efs-csi-driver v1.7.7), it works immediately (same Helm values)

**Environment**
- Kubernetes version: `v1.29` (Server version: `v1.29.1-eks-b9c9ed7`)
- Driver version: `v2.0.2`
- Helm Chart version: `v3.0.3`

**Please also attach debug logs to help us better diagnose**

Is the "Enable debug logging for efs-utils" section of https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting still up-to-date? Since efs-utils replaced stunnel with efs-proxy, is the described procedure still supposed to work? It didn't change anything in the log outputs for me. I did increased `logLevel` to `5` in the Helm values, though. This is the Log from the efs-csi-node Pod (efs-plugin container):

```
E0503 08:47:46.370467       1 driver.go:106] GRPC error: rpc error: code = Internal desc = Could not mount "fs-00bbbbbbbbbbbbbbb:/" at "/var/lib/kubelet/pods/88a4322e-686d-4eae-a045-77edd4f4e07b/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673948/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o accesspoint=fsap-02d4502d4502d4502,tls fs-00bbbbbbbbbbbbbbb:/ /var/lib/kubelet/pods/88a4322e-686d-4eae-a045-77edd4f4e07b/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673948/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
Mount attempt 1/3 failed due to timeout after 15 sec, wait 0 sec before next attempt.
Mount attempt 2/3 failed due to timeout after 15 sec, wait 0 sec before next attempt.
b'mount.nfs4: Connection timed out'
```

Compared to v2.5.7 / v1.7.7 where it just works:

```
I0503 07:01:45.024974       1 mount_linux.go:219] Mounting cmd (mount) with arguments (-t efs -o accesspoint=fsap-02d4502d4502d4502,tls fs-00bbbbbbbbbbbbbbb:/ /var/lib/kubelet/pods/f5c11c2c-ebef-4b00-8c7c-c8e8174546a6/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673048/mount)
I0503 07:01:55.800746       1 node.go:193] NodePublishVolume: /var/lib/kubelet/pods/f5c11c2c-ebef-4b00-8c7c-c8e8174546a6/volumes/kubernetes.io~csi/pvc-2e0b9760-eb6e-4b5e-a48a-f54919673048/mount was mounted
```

If I should provide more details, I'll happily do so - just tell me how :)
