### ISSUE TITLE
Add Tags Configurations In dynamically Provisioning Access Points

### ISSUE THREAD

**Issue by joannazhou888** [kubernetes-sigs/aws-efs-csi-driver#1346]
**Is your feature request related to a problem? Please describe.**
When using dynamic provisioning, the access point created only has the tag `efs.csi.aws.com/cluster = true`. 
**Describe the solution you'd like in detail**

We would like to be able to config tags in PVC 

```
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: xx
    storageClassName: xxx
    volumeMode: Filesystem
    tags:
       - service_name : my_service
       - team: infra
       - environment: development
       ... 
```

**Describe alternatives you've considered**
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/700 

**Additional context**
