### ISSUE TITLE
Delete Released PV will not clear it's access point

### ISSUE THREAD

**Issue by LuoYuWuSheng** [kubernetes-sigs/aws-efs-csi-driver#1375]
/kind bug

**What happened?**
when you delete Released PV, efs csi will not clear it's access point. This will case AP num increase quickly, and reach EFS AP limits which is 1000.

**What you expected to happen?**
when delete Released PV, efs csi should clear it's access point. 

**How to reproduce it (as minimally and precisely as possible)?**
create an pv use below SC，and delete it. Then you will still find ap in efs.
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc-dynamic
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: "777"
  fileSystemId: xxxxxxxxxxxxxxxxx
  gid: "1000"
  provisioningMode: efs-ap
  uid: "1000"
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: aws-efs-csi-driver:v1.7.4

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)
