### ISSUE TITLE
Incorrect namespace in ClusterRoleBinding manifest

### ISSUE THREAD

**Issue by eugenea** [kubernetes-sigs/aws-efs-csi-driver#1436]
/kind bug

**What happened?**

I noticed in `/deploy/kubernetes/base/node-serviceaccount.yaml` file ClusterRoleBinding targets `default` namespace:

```
subjects:
  - kind: ServiceAccount
    name: efs-csi-node-sa
    namespace: default
```

**What you expected to happen?**

I expect it to probably be a `kube-system` namespace:

```
subjects:
  - kind: ServiceAccount
    name: efs-csi-node-sa
    namespace: kube-system
```

**How to reproduce it (as minimally and precisely as possible)?**

N/A

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)
