### ISSUE TITLE
Feature - Dynamically Create EFS

### ISSUE THREAD

**Issue by dms486** [kubernetes-sigs/aws-efs-csi-driver#1566]
**Is your feature request related to a problem? Please describe.**
A dynamic mode where the EFS CSI driver dynamically create EFS file systems based on PV requests.

**Describe the solution you'd like in detail**
A Storage Class could be defined with specific EFS file system parameters, like the following.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-dynamic
  accessPoints:
    basePath: "/dynamic_provisioning" # optional
    subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  fileSystemType: "regional"
  automaticBackups: "true"
  lifecycleManagement:
    transitionInfrequentAccess: "30" # number of days since last accessed
    transitionArchive: "90" # number of days since last accessed
    transitionStandard: "None"
  encryptionAtRest: "true"
  throughputMode: "enhanced"
  vpc: "vpc-123"
  mountTargets:
    - availabilityZone: "us-east-1a"
      subnetID: "subnet-123"
      securityGroups:
        - "sg-123"
    - availabilityZone: "us-east-1b"
      subnetID: "subnet-456"
      securityGroups:
        - "sg-123"
   fileSystemPolicy:
     Version: "2012-10-17"
     Statement:
       - Effect: ...
         Principal: ...
         Action: ...
         Resource: ...
```

Then applications could request storage through a PVC. Annotations could be used to set parameters for an EFS Access Point

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
  annotations:
    efs.csi.aws.com/directoryPerms: "700"
    efs.csi.aws.com/uid: "1000"
    efs.csi.aws.com/gid: "1000"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi # required for spec but not enforced
```

**Describe alternatives you've considered**
Dynamic Provisioning: doesn’t let you set the uid/gid per PVC and it also shares an underlying EFS file system.

CDK and Static Provisioning: can create the EFS file system, EFS Access Point, storage class, and PV with CDK. Then create the PVC with the application deployment. But it’s not quite as dynamic
