### ISSUE TITLE
efs-plugin is not able to delete multiple dynamic volumes in a short period of time

### ISSUE THREAD

**Issue by amatas-stuart** [kubernetes-sigs/aws-efs-csi-driver#1612]
/kind bug

**What happened?**
We have a setup in AWS EKS 1.30 with the `aws-efs-csi-driver` addon enabled with the latest version 2.1.6 (also tested with 2.1.7).

The creation of a number (~20) of the EFS dynamic volumes works fine, but the deletion of such number of volumes breaks the controller and leaves the EFS access points and the PVs intact. The addon reaches a state where either it is unable to delete the PVs or create new ones with the same storage class.

**What you expected to happen?**
The controller is able to delete the PVs and the EFS access points.

**How to reproduce it (as minimally and precisely as possible)?**
Storageclass:
```
metadata:
  name: efs-generic
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
mountOptions:
- tls
parameters:
  basePath: /d
  directoryPerms: "700"
  ensureUniqueDirectory: "true"
  fileSystemId: fs-0XXXXXXXXXXXXd
  gidRangeEnd: "2000"
  gidRangeStart: "1000"
  provisioningMode: efs-ap
  reuseAccessPoint: "false"
  subPathPattern: ${.PVC.name}
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Apply pods and pvcs of the yaml attached, and then delete all of them at the same time.

[output.yaml.txt](https://github.com/user-attachments/files/19446491/output.yaml.txt)

It looks like the driver struggles to connect to the AWS API to manage the access points, reaching a high usage of memory and potentially being OOMKilled if it reaches the memory limit.

[efs-plugin-logs.txt](https://github.com/user-attachments/files/19447889/efs-plugin-logs.txt)

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): v1.30.10-eks-bc803b4
- Driver version: 2.1.6, 2.1.7
