### ISSUE TITLE
Failure on Mount

### ISSUE THREAD

**Issue by AzySir** [kubernetes-sigs/aws-efs-csi-driver#1614]
/kind bug

**What happened?**

The mount is not completing - there is no clear indicator why, it just says mount failed exit status 32

**What you expected to happen?**

The mount to mount my pods with no issues

**How to reproduce it (as minimally and precisely as possible)?**

Running this code here:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${app}-${env}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${app}-${env}-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${app}-${env}-pv
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
    - iam
    - tls
  storageClassName: ${app}-${env}-sc
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${volume}
  volumeAttributes:
    encryptInTransit: "false"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ${app}-${env}-sc
mountOptions:
    - iam
    - tls
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${volume}
  directoryPerms: "700"
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Please also attach debug logs to help us better diagnose**

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)
