### ISSUE TITLE
Specify filesystemID from kubernetes secret

### ISSUE THREAD

**Issue by zevisert-aaico** [kubernetes-sigs/aws-efs-csi-driver#1615]
**Is your feature request related to a problem? Please describe.**

It's annoying to specify the EFS filesystemID to PVs or StorageClasses

**Describe the solution you'd like in detail**

I would like to be able to populate the filesystemID from a secret or configmap, maybe like: 

```yaml
kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata: 
  name: efs-sc 
provisioner: efs.csi.aws.com 
parameters: 
  provisioningMode: efs-ap 
  fileSystemIdSecretRef: # <-- this is the ask
    name: my-filesystem-secret
    namespace: some-namespace
    key: id
```

**Describe alternatives you've considered**
- None, I guess. We just hard-code the filesystem ID into our PV

**Additional context**

The ask is similar to #1052 where the OP is creating a resource in terraform with some specific AWS tags. I'm using crossplane and we deploy a filesystem from this custom resource:

```yaml
apiVersion: efs.aws.upbound.io/v1beta1
kind: FileSystem
metadata:
  name: filesystem
spec:
  providerConfigRef:
    name: crossplane-aws
  forProvider:
    region: ${AWS_REGION}
    creationToken: ${EKS_CLUSTER_NAME}-filesystem
    performanceMode: generalPurpose
    throughputMode: bursting
```

It has the ability to write details about the created resource to a secret, so this is an in-cluster discovery mechanism instead of discovering via AWS tags

**Comment by wangnyue** [comment]
Hello, thanks to bring this up. We will take this as backlog item.

**Comment by zevisert-aaico** [comment]
Great news @wangnyue, thank you!

**Comment by zevisert** [comment]
I looked at this a bit today, I don't think my request will work as is, since [`v1.StorageClass.parameters` is of type `map[string]string`](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/#StorageClass), and my request was so populate the ID from a structured format like: 

```yaml
...
parameters: 
  provisioningMode: efs-ap 
  fileSystemIdSecretRef: # <-- this is the ask
    name: my-filesystem-secret
    namespace: some-namespace
    key: id
```

Instead, maybe it becomes something like:

```yaml
...
parameters: 
  provisioningMode: efs-ap 
  fileSystemIdSecretRef: <namespace?>/<name>/<key>
```

**Comment by ghost** [comment]
I looked at this a bit today, I don't think my request will work as is, since [`v1.StorageClass.parameters` is of type `map[string]string`](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/#StorageClass), and my request was so populate the ID from a structured format like: 

```yaml
...
parameters: 
  provisioningMode: efs-ap 
  fileSystemIdSecretRef: # <-- this is the ask
    name: my-filesystem-secret
    namespace: some-namespace
    key: id
```

Instead, maybe it becomes something like:

```yaml
...
parameters: 
  provisioningMode: efs-ap 
  fileSystemIdSecretRef: <namespace?>/<name>/<key>
```

/remove-lifecycle rotten
