### ISSUE TITLE
All existing mounts hang after the EKS Driver container is replaced on a given node

### ISSUE THREAD

**Issue by jqmichael** [kubernetes-sigs/aws-efs-csi-driver#178]
/kind bug

**What happened?**
After the EKS driver container is replaced (i.e. by terminating the driver process or upgrading the driver to a new image), all existing mounts on that node hang indefinitely. 

**What you expected to happen?**
Existing mounts should still be functioning after a new EKS driver container is launched to the same node. 

**How to reproduce it (as minimally and precisely as possible)?**
Deploy EFS driver from master and create a pod using the encryption_in_transit example. So far so good. 

exec into the EFS CSI driver container and kill the driver process. 
```
kubectl exec $(kubectl get po -l app=efs-csi-node -n kube-system -o jsonpath='{.items[0].metadata.name}') -n kube-system -it efs-plugin -- sh

kill 1
```

Reading file from the EFS mount hangs indefinitely. 
```
kubectl exec -ti efs-app -- tail -f /data/out.txt
```

**Anything else we need to know?**:
Watch dog log:
```
2020-06-03 20:13:23,191 - INFO - Starting TLS tunnel: "/usr/bin/stunnel /var/run/efs/stunnel-config.fs-b6654c1c.var.li
b.kubelet.pods.d20ab7da-b516-4d8c-a397-3fd3f6d8616c.volumes.kubernetes.io~csi.efs-pv1.mount.20309"
2020-06-03 20:13:23,222 - INFO - Started TLS tunnel, pid: 1996

2020-06-03 20:13:25,288 - WARNING - Child TLS tunnel process 1996 has exited, returncode=1
```
Manually invoking the stunnel command gave me the following error:
```
/etc/amazon/efs/privateKey.pem: No such file or directory (2)
Service [efs]: Failed to initialize SSL context
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.16
- Driver version: master

**Comment by wongma7** [comment]
mentioned this bug here "Plus there is one bug on our (driver) side that needs to be fixed first, something to do with how a newer version of the efs mount helper writes private keys that need to be persisted (but this one does not affect any released versions of the driver)." https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/166#issuecomment-640932009 (just linking for reference)

**Comment by jqmichael** [comment]
We could the see behavior with he old version of efs-utils only if customer enabled IAM and access-point. But with https://github.com/aws/efs-utils/commit/41cd0384b0ea859b996f27ad0d646af9c27f8225, efs-utils started creating client cert for all TLS settings since it relies on client cert to report client info.

**Comment by farshad-hobsons** [comment]
@wongma7 , with `amazon/aws-efs-csi-driver:latest` (commit-id https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/f66f6a2acb7842d8106eb66f6cbe9b99b6c4e702), I am still experiencing the mount-hang on all existing mounts when I bounce the csi pod.

```bash
# aws-efs-csi-driver --version
{
  "driverVersion": "v0.4.0-dirty",
  "gitCommit": "f66f6a2acb7842d8106eb66f6cbe9b99b6c4e702",
  "buildDate": "2020-06-17T23:47:16Z",
  "efsClientSource": "k8s",
  "goVersion": "go1.13.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
My csi-driver daemonset manifest:
```yaml
apiVersion: extensions/v1beta1                                                                                                                                                                                                     [102/181]
kind: DaemonSet
metadata:
  name: efs-csi-node
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: efs-csi-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efs-csi-node
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --v=5
        env:
        - name: CSI_ENDPOINT
          value: unix:/csi/csi.sock
        image: amazon/aws-efs-csi-driver:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 3
        name: efs-plugin
        ports:
        - containerPort: 9809
          name: healthz
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /var/run/efs
          name: efs-state-dir
        - mountPath: /etc/amazon/efs
          name: efs-utils-config
      - args:
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/efs.csi.aws.com/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
        imagePullPolicy: IfNotPresent
        name: csi-driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        image: quay.io/k8scsi/livenessprobe:v2.0.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/efs.csi.aws.com/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/run/efs
          type: DirectoryOrCreate
        name: efs-state-dir
      - hostPath:
          path: /etc/amazon/efs
          type: DirectoryOrCreate
        name: efs-utils-config
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
