### ISSUE TITLE
Is it possible to use EFS CSI driver just with SC and PVC ?

### ISSUE THREAD

**Issue by przemolb** [kubernetes-sigs/aws-efs-csi-driver#211]
I am looking for a way to provision volumes on EKS similar to Azure k8s (AKS). They have `azure-file` (which is basically SMB) and I can create shared filesystems using just storage class and pvc:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysc
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysc
  resources:
    requests:
      storage: 1Gi
```
As you can see I can allocate `pvc` without defining `pv`.
Is it possible to achieve the same (no PVs) using EFS CSI driver ?
