### ISSUE TITLE
Helm support for node affinity

### ISSUE THREAD

**Issue by Saberos** [kubernetes-sigs/aws-efs-csi-driver#234]
**Is your feature request related to a problem?/Why is this needed**
I'm running a hybrid EKS cluster with both Fargate nodes and an EC2 node group. As Fargate does not currently support persistent volumes or CSI drivers, I would like to prevent the Daemonset from trying to deploy to Fargate nodes, as the pods scheduled on the Fargate nodes will fail to start.

/feature

**Describe the solution you'd like in detail**
This can be achieved by using affinity on the Daemonset. For example:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
```

I would like the ability to configure this nodeAffinity on the Daemonset included in the Helm chart. Alternatively, perhaps the above nodeAffinity could perhaps be included by default as Fargate is currently not supported.

**Describe alternatives you've considered**
Ignoring the failed pods scheduled to the Fargate nodes, or manually deploying EFS CSI driver instead of using the Helm chart.

**Additional context**
I did create a PR for this change (https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/233), but I closed it since the signing process of the  CNCF CLA is a bit more involved than I feel comfortable with, especially for such a small change.
