### ISSUE TITLE
Access Mode of ReadWriteOnce does not work as expected

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/aws-efs-csi-driver#263]
/kind bug

**What happened?**
Based on the [Kubernetes PV docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes), access mode of `ReadWriteOnce` claims that the volume can be mounted as read-write by a single node. However, I have observed that this is not the case.

**What you expected to happen?**
I expected that when the PV/PVC is defined with an access mode of `ReadWriteOnce`, deployment across multiple nodes should face issues.

**How to reproduce it (as minimally and precisely as possible)?**
I have provided the YAML below. Please note that `volumeHandle` value needs to be replaced with your EFS ID.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: efs-pvc
    namespace: default
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <REDACTED -- REPLACE HERE>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-writer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-writer
  template:
    metadata:
      labels:
        app: nfs-writer
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - something
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nfs-writer
        image: centos
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: efs-storage
          mountPath: /data
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-once
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: efs-pvc-once
    namespace: default
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <REDACTED -- REPLACE HERE>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-once
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  volumeName: efs-pv-once
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-writer-once
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-writer-once
  template:
    metadata:
      labels:
        app: nfs-writer-once
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - something
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nfs-writer-once
        image: centos
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: efs-storage
          mountPath: /data
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc-once
```

**Anything else we need to know?**:
```
 kubectl get pods -owide
NAME                               READY   STATUS    RESTARTS   AGE     IP               NODE                                           NOMINATED NODE   READINESS GATES
nfs-writer-698cfb558-lh4jw         1/1     Running   0          2m40s   192.168.34.10    ip-192-168-55-250.us-west-1.compute.internal   <none>           <none>
nfs-writer-698cfb558-nmgts         1/1     Running   0          2m40s   192.168.79.25    ip-192-168-89-112.us-west-1.compute.internal   <none>           <none>
nfs-writer-once-679689ddb4-66tpt   1/1     Running   0          2m40s   192.168.92.241   ip-192-168-89-112.us-west-1.compute.internal   <none>           <none>
nfs-writer-once-679689ddb4-9m6rz   1/1     Running   0          2m40s   192.168.49.156   ip-192-168-55-250.us-west-1.compute.internal   <none>           <none>
```
**Environment**
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version: `1.0` -- Deployed using `kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.0"`
