### ISSUE TITLE
efs-csi-node DaemonSet schedules to Fargate nodes with included example

### ISSUE THREAD

**Issue by benmccown-amz** [kubernetes-sigs/aws-efs-csi-driver#328]
/kind bug

**What happened?**

When following the EFS CSI documentation at [1] the efs-csi-node DaemonSet attempts to schedule to fargate based nodes if you are running any fargate workloads within your EKS cluster. This results in pods failing to deploy.

[1] https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**What you expected to happen?**

I would expect if I were to follow the documentation provided that the DaemonSet would not scheduled pods to fargate nodes unless it is required and built to function and schedule correctly.

**How to reproduce it (as minimally and precisely as possible)?**

1. Deploy EKS Fargate workloads within your cluster
2. Install the EFS CSI as per the docs at [1].
3. Get pods in kube-system to see the pods in the Pending status

[1] https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Anything else we need to know?**:

This is easily resolvable with a node anti affinity rule on the DaemonSet. I have a branch that I have tested which resolves this issue. I will further detail my changes in a PR.

**Environment**
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Driver version: 1.0

**Comment by benmccown-amz** [comment]
Modified spec.template.spec for node.yaml

```
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
```
