### ISSUE TITLE
Way to resolve EFS Name to the mount IP in same Availability zone

### ISSUE THREAD

**Issue by shubhamc183** [kubernetes-sigs/aws-efs-csi-driver#345]
**Way to resolve EFS Name to the mount IP in same Availability zone**
/feature

Right now, for attaching EFS present in cross VPC, we are using [HostAliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) to inject hostname resolution of EFS.

Previous Implementation: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/253

**We can only add one IP per EFS which will be used by all pods even they are in different AZs, which will have latency overhead**

Example,
```
hostAliases:
  fs-12345:
    ip: "172.11.22.333" # us-east-1a
    region: "us-east-1"
```
Here, my pods are in `us-east-1b`, `us-east-1c`, `us-east-1d`, `us-east-1e`, and `us-east-1f` AZs, but all will end up using the IP mount of `us-east-1a`, which will cause an overhead latency. 

I am thinking of an implementation like this.

```
hostAliases:
  fs-12345:
    region: "us-east-1"
    azs:
      us-east-1a: 172.11.22.333
      us-east-1b: 172.11.44.333
      us-east-1c: 172.11.55.333
      us-east-1d: 172.11.66.333
      us-east-1e: 172.11.77.333
      us-east-1f: 172.11.88.333
```
So, each daemon set has a hostname resolution pointing to IP in the same AZ to reduce the latency.

@jurgenweber @wgordon17 @2uasimojo @bysnupy
