### ISSUE TITLE
Unable to create multiple storage classes with Helm chart

### ISSUE THREAD

**Issue by NilsGriebner** [kubernetes-sigs/aws-efs-csi-driver#387]
/kind bug

**What happened?**
If multiple storageclasses are specified in `values.yaml` like
```
storageClasses:
  - name: efs-sc1
    parameters:
      provisioningMode: efs-ap
      fileSystemId: 123
      directoryPerms: "700"
  - name: efs-sc2
    parameters:
      provisioningMode: efs-ap
      fileSystemId: 345
      directoryPerms: "700"
```
the generated output lacks yaml separators. In my case the outcome was
```
...
---
# Source: aws-efs-csi-driver/templates/storageclass.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc1
provisioner: efs.csi.aws.com
parameters:
  directoryPerms: "700"
  fileSystemId: 123
  provisioningMode: efs-ap
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc2
provisioner: efs.csi.aws.com
parameters:
  directoryPerms: "700"
  fileSystemId: 345
  provisioningMode: efs-ap
---
...
```
**What you expected to happen?**
I expect two storageclasses to be created but only the last one gets created

**How to reproduce it (as minimally and precisely as possible)?**
Put my provided example code from `values.yaml` into the default values and run `helm install ...`

**Anything else we need to know?**:
No

**Environment**

- Kubernetes version (use `kubectl version`):
v1.18.9-eks-d1db3c

- Driver version:
1.2.0
