### ISSUE TITLE
User "system:serviceaccount:kube-system:efs-csi-controller-sa" cannot patch resource "events"

### ISSUE THREAD

**Issue by aliusmiles** [kubernetes-sigs/aws-efs-csi-driver#394]
/kind bug

**What happened?**
I've misconfigured StorageClass (set gidRangeStart and gidRangeEnd to the same value) and fount following message in controller logs: `User "system:serviceaccount:kube-system:efs-csi-controller-sa" cannot patch resource "events"  in API group "" in the namespace "dev"' (will not retry!)` [more logs](https://pastebin.com/raw/vzKdDTtb)

While it shows root cause in logs and everything works after fixing it, I'm not sure if error from above is supposed to happen in that case, since SA indeed [does not have patch permissions on events](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/f89b14367e2509738dc885ab82370152c2f4cf83/charts/aws-efs-csi-driver/templates/controller-serviceaccount.yaml#L32). 

**What you expected to happen?**
no errors 'cannot patch resource "events"'

**How to reproduce it (as minimally and precisely as possible)?**
create StorageClass with gidRangeStart and gidRangeEnd set to the same value:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxx
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "1000"
```

**Environment**
- Kubernetes version (use `kubectl version`): v1.19.6-eks-49a6c0
- Driver version: 1.2.0 (helm chart 1.2.2)
