### ISSUE TITLE
Failed to create access point: ValidationException

### ISSUE THREAD

**Issue by cf250024** [kubernetes-sigs/aws-efs-csi-driver#427]
All the pods are running fine for me. However I got the following error when I tried to create persistent volume dynamically.
This document (https://docs.aws.amazon.com/efs/latest/ug/efs-ug.pdf) says "ValidationException Returned if the AWS Backup service is not available in the Region in which the request was made. HTTP Status Code: 400". However my aws account uses us-west-2 which has the backup service.

If we look at https://docs.aws.amazon.com/efs/latest/ug/API_CreateAccessPoint.html
It seems 400 for bad request body doesn't have `"SecondaryGids": [ number ]` and rest of then are seems ok. Is this the case? 

Any suggestions what I did wrong and how to correct it? Thanks.

amazon/aws-efs-csi-driver:v1.2.0
k8s:1.18
helm chart version: 1.2.2

I0428 00:46:02.756018       1 cloud.go:132] Calling Create AP with input: {
  ClientToken: "pvc-9fa0fc9e-e90c-4ecc-a07e-4fd5e3c42e71",
  FileSystemId: "fs-5c7d785b",
  PosixUser: {
    Gid: 1001,
    Uid: 1001
  },
  RootDirectory: {
    CreationInfo: {
      OwnerGid: 1001,
      OwnerUid: 1001,
      Permissions: "700"
    },
    Path: "//efs-csi-ap-1001-84700a82-54a3-48b7-8c0b-e84674125fb9"
  },
  Tags: [{
      Key: "efs.csi.aws.com/cluster",
      Value: "true"
    }]
}
E0428 00:46:02.760320       1 driver.go:103] GRPC error: rpc error: code = Internal desc = Failed to create Access point in File System fs-5c7d785b : Failed to create access point: ValidationException:
	status code: 400, request id: 1d3a5104-fffb-473e-bfa5-7bc5fa0f87d6

**Comment by cf250024** [comment]
I followed the document and made it work for me. The ValidationException is not showing anymore.

**Comment by sergeye-boltinc** [comment]
Hi, can you please share how did you solve this issue?

**Comment by Colbize** [comment]
Was running into the same issue.
``` 
Warning    ProvisioningFailed  10s  efs.csi.aws.com_ip-x-x-x-x.x.x.x-x-x-x-x  failed to provision volume with StorageClass "dictionary-service-efs-sc": rpc error: code = Internal desc = Failed to create Access point in File System fs-xxxxxxxx : Failed to create access point: ValidationException: 
```
Turns out I was missing the `directoryPerms` key which is **not** optional.
snippet from helm chart:
```
{{ if .Values.efs_file_system_id }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "dictionary.fullname" . }}-efs-sc
  namespace: {{ .Values.namespace }}
  {{- include "dictionary.labels" . }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs_file_system_id }}
  directoryPerms: "777"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
{{ end }}
```
