### ISSUE TITLE
Add vol-metrics-opt-in argument to the helm chart to collect volume metrics

### ISSUE THREAD

**Issue by zodiac12k** [kubernetes-sigs/aws-efs-csi-driver#454]
**Is your feature request related to a problem?/Why is this needed**
By collecting metrics, you can see the volume used, available size, and more.

/feature

**Describe the solution you'd like in detail**
This can be solved by adding `vol-metrics-opt-in` as the default argument, or through additional argument values ​​such as `extraArgs`.
You should add `vol-metrics-opt-in` argument in the following deployment file.
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml

**Describe alternatives you've considered**
After installing the helm chart, edit the deployment as follows to add the argument.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-csi-controller
...
    spec:
      containers:
      - args:
        - --vol-metrics-opt-in=true
```

**Additional context**
Nothing
