### ISSUE TITLE
Lost volume after bounced the node pod

### ISSUE THREAD

**Issue by akunszt** [kubernetes-sigs/aws-efs-csi-driver#462]
/kind bug

**What happened?**
I'm in the middle of evaluating `aws-efs-csi`. I simulated a node pod failure/update process when the pods are bounced. I launched a test pod mounted an EFS PVC which wrote constantly to the EFS FileSystem. When the `efs-csi-node` pod bounced the test pod lost connectivity to the EFS and it never restored. Also every command issued on the host which accessed the mount point itself - for example a simple `df` - stuck. It looked like a typical NFS lost connection situation.

I'm using dynamic provisioning so one FileSystem with many AccesPoints.

**What you expected to happen?**

The EFS remains accessible when the `efs-csi-node` bounces. We used `efs-provisioner` before which just mounted the NFS filesystem and then let the Kubernetes handle it. I saw that `aws-efs-csi` uses `127.0.0.1` as the server which explains why everything stops working when the `efs-csi-node` has any issues.

```
127.0.0.1:/ /var/lib/kubelet/pods/0a00884f-eb72-41f5-b9c9-e8ed7a943716/volumes/kubernetes.io~csi/pvc-88c79104-4202-4914-a259-f92243bafb47/mount nfs4 rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,noresvport,proto=tcp,port=20376,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1 0 0
```

Is it possible to mount the EFS FileSystem directly to avoid this single point of failure on the local node?

**How to reproduce it?**

Create an EFS PVC and launch a pod - for example `alpine:3.13` or any other general would do. Mount the EFS into the pod.

This is just an example how to do it.
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: akunszt-test-efs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: aws-efs
---
apiVersion: v1
kind: Pod
metadata:
  name: akunszt-test
spec:
  restartPolicy: Never
  containers:
    - name: shell
      image: alpine:3.13
      command:
        - /bin/sh
      args:
        - "-c"
        - "apk update; apk add bash; while true; do sleep 60; done"
      volumeMounts:
        - name: pvc
          mountPath: /pvc
          readOnly: false
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: akunszt-test-efs
```
Exec into the pod - I use `bash` for the shell but that shouldn't matter - and execute the following command to constantly write to the PVC.
```sh
while true; do date '+%Y-%m-%d %H:%M:%S'; touch /pvc/a; sleep 0.2; done
```
Let it running and delete the `aws-efs-csi` pod running on the same node. The DaemonSet will re-create it instantly - like it would happen during an update - but the test pod will stuck/freeze, it won't retry - I waited about 20 minutes but even an `ls -l /pvc` freezes.

**Anything else we need to know?**:
It's possible - I hope - that I missed something during the deployment. Currently bouncing the `aws-efs-csi` pod could render the node unusable - for example monitoring or any other thing which uses just a `df` command in a script etc.

Also it blocks any intentional updates of the node pods as well as it will slowly kills/freezes every workload using EFS as the roll-out advances. Scaling down every Deployments/StatefulSets just to update `aws-efs-csi` is not an option. From the user's point of view this was unnoticeable before when we used `efs-provisioner`.

So I really hope that it's just me. In this case please point me to the right documentation or if it doesn't exist yet it's worth to add this scenario.

We are using `aws-vpc-cni` and `kiam`. We had to disable the `hostNetwork: true` in the chart to make it work at all but the pods still have routable IP addresses - assigned from the local VPC range - and can reach the EFS FileSystem directly.

**Environment**
- Kubernetes version: 1.21.1
- Driver version: 1.2.1
