### ISSUE TITLE
 can't evaluate field reclaimPolicy in type string with  helm template while installing

### ISSUE THREAD

**Issue by mmenarguezpear** [kubernetes-sigs/aws-efs-csi-driver#473]
/kind bug

**What happened?**
```
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver --values .values.yaml
Release "aws-efs-csi-driver" does not exist. Installing it now.
Error: template: aws-efs-csi-driver/templates/storageclass.yaml:20:18: executing "aws-efs-csi-driver/templates/storageclass.yaml" at <.reclaimPolicy>: can't evaluate field reclaimPolicy in type string
```
**What you expected to happen?**
Installation to work with values as provided in values.yaml
**How to reproduce it (as minimally and precisely as possible)?**
values.yaml
```
# Default values for aws-efs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: amazon/aws-efs-csi-driver
  tag: "v1.2.1"
  pullPolicy: IfNotPresent

sidecars:
  livenessProbe:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
      tag: v2.2.0-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}
  nodeDriverRegistrar:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
      tag: v2.1.0-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}
  csiProvisioner:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
      tag: v2.1.1-eks-1-18-2
      pullPolicy: IfNotPresent
    resources: {}

imagePullSecrets: []

## Controller deployment variables

controller:
  # Specifies whether a deployment should be created
  create: true
  # Number for the log level verbosity
  logLevel: 2
  # Add additional tags to access points
  tags: {}
    # environment: prod
  # region: us-east-1
  # Enable if you want the controller to also delete the
  # path on efs when deleteing an access point
  deleteAccessPointRootDir: false
  podAnnotations: {}
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # Specifies whether a service account should be created
  serviceAccount:
    create: true
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role
    name: efs-csi-controller-sa
    annotations: {}

## Node daemonset variables

node:
  # Number for the log level verbosity
  logLevel: 2
  hostAliases: {}
    # For cross VPC EFS, you need to poison or overwrite the DNS for the efs volume as per
    # https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-efs-utils-step3
    # implementing the suggested solution found here:
    # https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/240#issuecomment-676849346
    # EFS Vol ID, IP, Region
    # "fs-01234567":
    #   ip: 10.10.2.2
  #   region: us-east-2
  dnsPolicy: ClusterFirst
  dnsConfig: {}
    # Example config which uses the AWS nameservers
    # dnsPolicy: "None"
    # dnsConfig:
    #   nameservers:
  #     - 169.254.169.253
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  tolerations:
    - operator: Exists

storageClasses:
 - name: efs-sc
   annotations:
     # Use that annotation if you want this to your default storageclass
     storageclass.kubernetes.io/is-default-class: "true"
   mountOptions:
    - tls
   reclaimPolicy: "Delete"
   volumeBindingMode: "Immediate"
   parameters:
     provisioningMode: efs-ap
     fileSystemId: fs-xxxx
     directoryPerms: "700"
     gidRangeStart: "1000"
     gidRangeEnd: "2000"
     basePath: "/dynamic_provisioning"
```

Then install with helm chart version 2.0.0

```
helm upgrade --install aws-efs-csi-driver --namespace kube-system aws-efs-csi-driver/aws-efs-csi-driver --values ../repos/orchard/data-engineering/values.yaml
Release "aws-efs-csi-driver" does not exist. Installing it now.
Error: template: aws-efs-csi-driver/templates/storageclass.yaml:20:18: executing "aws-efs-csi-driver/templates/storageclass.yaml" at <.reclaimPolicy>: can't evaluate field reclaimPolicy in type string
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version: v1.2.1

**Comment by mmenarguezpear** [comment]
I see this was fixed on https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/362b5e6ab95d1078e92f46201fde6b36466e97ec

**Comment by mmenarguezpear** [comment]
Workaround:
```
storageClasses:
 - name: efs-sc
   annotations:
     # Use that annotation if you want this to your default storageclass
     storageclass.kubernetes.io/is-default-class: "true"
   mountOptions:
    - tls
   reclaimPolicy:
     reclaimPolicy: "Delete"
   volumeBindingMode:
     volumeBindingMode: "Immediate"
   parameters:
     provisioningMode: efs-ap
     fileSystemId: fs-xxx
     directoryPerms: "700"
     gidRangeStart: "1000"
     gidRangeEnd: "2000"
     basePath: "/dynamic_provisioning"
```
