### ISSUE TITLE
EFS Shared From AWS Account to Another AWS Account

### ISSUE THREAD

**Issue by ivialex-mcd** [kubernetes-sigs/aws-efs-csi-driver#482]
/kind bug

**What happened?**
I following step by step for this site https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html, and when I deploy the pod in EKS cluster show as image below. The pod don't create.

![image](https://user-images.githubusercontent.com/82114943/121259048-00d40580-c886-11eb-8358-cba651049c27.png)

**What you expected to happen?**

I would like to create the mount EFS inside my EKS Cluster.

**How to reproduce it (as minimally and precisely as possible)?**
I would like to know if possible to mount EFS (This EFS was created in another AWS Account and shared in my AWS Account, and we did too the VPC Peering between the two AWS Account) within my EKS Cluster. 
Note: I can mount EFS in EC2 Instance. I did these steps below for my EC2 Instance and works for me.

$ echo "[IP] [FS-ID].efs.us-east-1.amazonaws.com" | sudo tee -a /etc/hosts
$ cd /
$ mkdir efs
$ sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport [FS-ID].efs.us-east-1.amazonaws.com:/ /efs

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.19
- Driver version: v1.2.0

**Comment by wongma7** [comment]
can you try https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/cross_account_mount? you need driver v1.3.0 which we just released

**Comment by ivialex-mcd** [comment]
> apiVersion: storage.k8s.io/v1
> metadata:
>   name: efs-sc
> provisioner: efs.csi.aws.com
> mountOptions:
>   - tls
> parameters:
>   provisioningMode: efs-ap
>   fileSystemId: fs-1234abcd
>   directoryPerms: "700"
>   gidRangeStart: "1000"
>   gidRangeEnd: "2000"
>   basePath: "/dir/subDir"
>   az: us-east-1aapiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-b2e462fb
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/RFM2/RFM2PackageGenDir"
  az: us-east-1a

**Comment by wongma7** [comment]
@ivialex-mcd you have to delete and recreate the storageclass with fileSystemId edited and the secret name+namespace, I just realized our example is missing the secret name+namespace. The secret created in step 2 needs to be referred to in the storageclass with these parameters:
```
  csi.storage.k8s.io/provisioner-secret-name: x-account # optional, required for cross-account mount. Should be unique per storage class
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system # option, required for cross-account mount
```

So in sum, the storageclass should be someting like this:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
  - iam
  - az=us-east-1f # optional, allows cross AZ mount
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01234abcd # <- your fs here
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional
  az: us-east-1f # optional, used by controller to provide a preferred mount-target AZ
  csi.storage.k8s.io/provisioner-secret-name: x-account # <- your secret here
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system  # <- your secret here
```
There is a another example here :https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/470
