### ISSUE TITLE
Add x-AZ mount support for efs-csi-driver to helm chart

### ISSUE THREAD

**Issue by spanktar** [kubernetes-sigs/aws-efs-csi-driver#496]
Thanks to @kbasv for getting [multi-AZ support](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/425) into the driver, now it needs to make its way into the helm chart:

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/values.yaml#L81-L89

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/node-daemonset.yaml#L24-L31

**Comment by kbasv** [comment]
@spanktar 

For cross-AZ mounts within the same AWS account, you can provide `az=<desiredAZ>` under mount options either in storage class or PV. No additional changes are required.

For cross-account mount through vpc-peering, you may skip the above host alias option and instead follow the [setup](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/cross_account_mount#prerequisite-setup) provided in cross-account mount example (VPC peering & grant necessary IAM permissions).
Once the setup is in place, you can deploy your storage class and perform cross-account mounting through dynamic provisioning.

**Comment by spanktar** [comment]
I guess I should explain a little more :-)

First, we create the mount targets with Terraform. Note the `count` and that each subnet that is counted is in a different AZ:

```
resource "aws_efs_mount_target" "efs_shared_storage_mount" {
  count           = length(local.private_subnets)
  file_system_id  = aws_efs_file_system.efs_shared_storage.id
  security_groups = [aws_security_group.eks_cluster_efs.id]
  subnet_id       = aws_subnet.private[count.index].id
}
```

We export the EFS_MOUNT_IP from Terraform, but we only export 1 of 3 b/c there was no support for multiple (note the `[0]`)

```
output "efs_mount_ip" {
  value = aws_efs_mount_target.efs_shared_storage_mount[0].ip_address
}
```

Then we install this driver like so
```
  helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=${ECR_REPO}/eks/aws-efs-csi-driver \
    --set serviceAccount.controller.create=true \
    --set serviceAccount.controller.name=efs-csi-controller-sa \
    --set hostAliases.${EFS_FILESYSTEM_ID}.ip=${EFS_MOUNT_IP} \
    --set hostAliases.${EFS_FILESYSTEM_ID}.region=${MDL_AWS_REGION}
```

So I'm not sure how to adjust this to use the other 2 mounts that we create. Our mounts are not cross-account.

This is the YAML we use to implement the StorageClass:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
mountOptions:
  - rsize=1048576
  - wsize=1048576
  - soft
  - timeo=150
  - retrans=2
  - noresvport
provisioner: efs.csi.aws.com
parameters:
  directoryPerms: "700"
  fileSystemId: EFS_FILESYSTEM_ID
  provisioningMode: efs-ap
```

If we're using 3 AZs, how do we define all three?
