### ISSUE TITLE
accessModes: ReadOnlyMany not working

### ISSUE THREAD

**Issue by pporee** [kubernetes-sigs/aws-efs-csi-driver#502]
/kind bug

**What happened?**
When using a PV with access mode ReadOnlyMany got error: 
`Warning  FailedMount  3s (x4 over 6s)  kubelet            MountVolume.SetUp failed for volume "pv" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = InvalidArgument desc = Volume capability not supported`

Looks like this issue : https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/121
Thanks for your help

**What you expected to happen?**
Pod can mount the PV.
**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:
PV and PVC are bound.
PV config:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: connectors-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxx
```
PVC config: 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connectors-claim
  namespace: connectors-efs
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
```
POD config
```
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  namespace: connectors-efs
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: connectors-claim
```
**Environment**
- Kubernetes version (use `kubectl version`): 1.17
- Driver version: 1.3.2

**Comment by Yambottle** [comment]
Having the same issue here as well, so spent some time to trace the error message in the source code:

The error message raised [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/78b89dbbfa9d1cde80733e362b8da43600ca26c4/pkg/driver/node.go#L65)

It's calling `validateAccessMode` [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/78b89dbbfa9d1cde80733e362b8da43600ca26c4/pkg/driver/node.go#L318)

This function will reference `volumeCapAccessModes` [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/78b89dbbfa9d1cde80733e362b8da43600ca26c4/pkg/driver/node.go#L35) There are only `VolumeCapability_AccessMode_SINGLE_NODE_WRITER`, `VolumeCapability_AccessMode_MULTI_NODE_MULTI_WRITER`. These two are imported from [here](https://github.com/container-storage-interface/spec/blob/5b0d4540158a260cb3347ef1c87ede8600afb9bf/lib/go/csi/csi.pb.go#L141)

I feel like this shouldn't be a bug, it just doesn't support read-only yet. Then the question will be "Is there any work around?"

**Comment by ajoslin103** [comment]
bmp

This problem really killed what would have been an otherwise very clean deployment for me.  AWS EFS Replication was giving me a failover site in another region using a no-code solution.

Is there anywhere we can vote for features/fixes ?

**Comment by Preen** [comment]
+1

**Comment by alankan-finocomp** [comment]
Having exactly the same issue here +1.
Is there any plan to support `VolumeCapability_AccessMode_MULTI_NODE_READER_ONLY` in near future?

**Comment by james-jasvin** [comment]
**Workaround!**

We ran into a similar issue and I'm not sure if this workaround has already been mentioned but using the `ro` mount option just straight up worked for us with EFS' static provisioning and I assume it will work for dynamic provisioning as well if you just specify the mount option as part of the StorageClass.

PV definition:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-rwx
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # CSI driver requires this, we enforce RO via mount options
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Empty string to prevent dynamic provisioning
  mountOptions:
    - ro              # Read-only mount option
    - tls             # Use TLS for encryption in transit (recommended)
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <efs-id>  # Your EFS filesystem ID
```

PVC definition:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-rwx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
```

To validate whether the volume mount was indeed read-only, I tested it out with a pod
```
apiVersion: v1
kind: Pod
metadata:
  name: efs-test-pod-rwx
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: efs-claim-rwx
  containers:
    - name: my-container
      image: ubuntu
      command: ["/bin/bash"]  # Add this line
      stdin: true             # Add this line
      tty: true               # Add this line
      volumeMounts:
        - mountPath: /shared
          name: my-volume
```
Exec into the pod and can see that you cannot write to the `/shared` path
```
❯ kubectl exec efs-test-pod-rwo -it -- bash -il                                                
root@efs-test-pod-rwo:/# cd /shared/
root@efs-test-pod-rwo:/shared# touch test.txt
touch: cannot touch 'test.txt': Read-only file system
```

An alternate approach can be to use recursive read-only mounts that K8s now ships with: https://kubernetes.io/blog/2024/04/23/recursive-read-only-mounts/
