### ISSUE TITLE
PodSecurityPolicy and Daemonset Service Account for Helm Chart

### ISSUE THREAD

**Issue by Reinkaos** [kubernetes-sigs/aws-efs-csi-driver#503]
Hey,

Not sure if this is a bug or a feature, have put it here as it's preventing me from using the chart but it could be considered a feature. 

**What happened?**

I am unable to get the Node CSI Driver deployed using the Helm Chart because it does not come with it's own Pod Security Policy, does not comply with my clusters default pod security policy and there is no service account available with the daemonset that I can bind my own policy too. 

**What you expected to happen?**

The chart to deploy an appropriate service account and pod security policy for the controller and the daemonset or it comes with a service account that can be used for binding the policy. 

**How to reproduce it (as minimally and precisely as possible)?**

You can reproduce it by implementing a PSP like so:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restrictive
spec:
  privileged: false
  hostNetwork: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  ```

and binding it to your authenticated group:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restrictive-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - restrictive
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restrictive-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restrictive-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

and then trying to deploy the chart, which will result in this error on the controller and the daemonset:

```
PodSecurityPolicy: unable to admit pod: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 9809: Host port 9809 is not allowed to be used. Allowed ports: []]
```

I was able to fix the controller by binding my own policy to the service account that comes with it. 

Thanks for your help,
Richard
