### ISSUE TITLE
Unable to mount an EFS volume using Access Points

### ISSUE THREAD

**Issue by edoardo-c** [kubernetes-sigs/aws-efs-csi-driver#504]
/kind bug

**What happened?**
I seem to be unable to connect to an EFS volume using an access point. It works fine if I mount on the EFS volume root.

**What you expected to happen?**
I expected to be able to connect to the EFS volume using an Access point.

**How to reproduce it (as minimally and precisely as possible)?**
I have the following basic settings (test.yaml):

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxxxxxxxxxxxxxx::fsap-zzzzzzzzzzzzzzzzz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: app
    image: centos
    command: ['sleep', '3600']
    # command: ["/bin/sh"]
    # args: ["-c", "while true; do echo $(date -u) >> /dir1/out.txt; sleep 5; done"]
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
    volumeMounts:
    - name: efs-volume-1
      mountPath: /dir1
  volumes:
  - name: efs-volume-1
    persistentVolumeClaim:
      claimName: pvc1
```
```
$ Kubectl apply -f test.yaml
storageclass.storage.k8s.io/efs-sc created
persistentvolume/pv1 created
persistentvolumeclaim/pvc1 created
pod/myapp created
```
```
$ kubectl describe pod/myapp|tail -n 9
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    8m42s                 default-scheduler  Successfully assigned kube-system/myapp to ip-10-11-12-13
  Warning  FailedMount  25s (x12 over 8m42s)  kubelet            MountVolume.SetUp failed for volume "pv1" : rpc error: code = Internal desc = Could not mount "fs-xxxxxxxxxxxxxxxxx:/" at "/var/lib/kubelet/pods/a5a6023e-ca93-455e-929b-eebf07bc55b9/volumes/kubernetes.io~csi/pv1/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o accesspoint=fsap-zzzzzzzzzzzzzzzzz,tls fs-xxxxxxxxxxxxxxxxx:/ /var/lib/kubelet/pods/a5a6023e-ca93-455e-929b-eebf07bc55b9/volumes/kubernetes.io~csi/pv1/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
b'mount.nfs4: access denied by server while mounting 127.0.0.1:/'
```

**Anything else we need to know?**:
Not that I can think of other than I have made quite a few tries so it is possible that something I previously did is causing a problem.

**Environment**
- Kubernetes (kubeadm) Server Version: v1.19.4
- AWS EFS CSI driver image: amazon/aws-efs-csi-driver:v1.3.1
