### ISSUE TITLE
changing group id not allowed. EFS Dynamic provisioning.

### ISSUE THREAD

**Issue by harshdevl** [kubernetes-sigs/aws-efs-csi-driver#520]
hello  so i have dynamic provisioning EFS provided as Pv in deployment files for wordpress project.

and i need to change the permissions of my mounted folder which is /var/www/html

what i have done : 

-  here is my dynamic provisioning file 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-cxxx0
  directoryPerms: "777"
  gidRangeStart: "1"
  gidRangeEnd: "7000000"
  basePath: "/demo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sc
  resources:
    requests:
      storage: 5Gi
```

- here is my deployment file 

```kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpressss
  namespace: test
  labels:
    app: wordpressss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpressss
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpressss
        tier: frontend
    spec:
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs-claim
      # securityContext:
      #     fsGroup: 33
      #     runAsGroup: 33
      #     runAsUser: 0
      #     fsGroupChangePolicy: "Always"
      initContainers:
      - name: nfs-fixer
        image: wordpress:latest
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: efs-pvc
          mountPath: "/var/www/html"
        command:
        - sh
        - -c
        - (chmod 0775 /var/www/html; chgrp 33 /var/www/html)
      containers:
      - name: wordpressss
        image: wordpress:latest
        name: wordpressss
        resources:
          requests:
            memory: "128Mi"
            cpu: "70m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: efs-pvc
          mountPath: "/var/www/html"
        # securityContext:
        #   fsGroup: 33
        #   runAsGroup: 33
        #   runAsUser: 0
        #   fsGroupChangePolicy: "Always"
```

i have also tried using SecurityContext as suggested in official documentation but for some reason it won't work.

Finally my IAM role policy

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:DescribeAccessPoints",
        "elasticfilesystem:DescribeFileSystems"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "elasticfilesystem:CreateAccessPoint"
      ],
      "Resource": "*",
      "Condition": {
        "StringLike": {
          "aws:RequestTag/efs.csi.aws.com/cluster": "true"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": "elasticfilesystem:DeleteAccessPoint",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:ResourceTag/efs.csi.aws.com/cluster": "true"
        }
      }
    }
  ]
}
```

to deploy efs-sci-drivers i have followed AWS documentation which works perfectly with other types of volume mount and dynamic volume type but it wont allow me to change permission which i need to run wordpress site. 

any suggestions will be appreciated.

/triage support
