### ISSUE TITLE
Add statefulset volumeClaimTemplates dynamic provisioning example

### ISSUE THREAD

**Issue by Ashtonian** [kubernetes-sigs/aws-efs-csi-driver#541]
**Is your feature request related to a problem?/Why is this needed**
I would like to use this driver with a statefulset and dynamic provisioning where each pod gets its own volume and that will be remounted when the pod is recreated. IE pod_1 -> vol_1, pod_2 -> vol_2. Is this possible with the current, driver can we document it? 

/feature

**Comment by fangj99** [comment]
It seems working with the solution provided by "wongma7" in the following issue: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/319 and this MR: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/297/files#diff-e6d7365a4dbfc5cab12e69340000ad1fa8ad965ec63b2f80f8811ad2a84dca05

One problem is my eks IAM role missing the permission to create efs access point, after resolved that, statefulset's volumeClaimTemplates will work with efs
### Error Msg
```
 failed to provision volume with StorageClass "efs-sc-dyna": rpc error: code = Unauthenticated desc = Access Denied. Please ensure you have the right AWS permissions: Access denied
```
### Working Sample
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-dyna
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: <EFS ID>
  directoryPerms: "777"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: efs-app-sts
spec:
  selector:
    matchLabels:
      app: test-efs
  serviceName: efs-app
  replicas: 3
  template:
    metadata:
      labels:
        app: test-efs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: linux
        image: amazonlinux:2
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /efs-data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: efs-storage
          mountPath: /efs-data
  volumeClaimTemplates:
  - metadata:
      name: efs-storage
    spec:
      accessModes: [ReadWriteMany]
      storageClassName: efs-sc-dyna
      resources:
        requests:
          storage: 1Gi

```
