### ISSUE TITLE
uid/gid Parameters Ignored

### ISSUE THREAD

**Issue by iAnomaly** [kubernetes-sigs/aws-efs-csi-driver#567]
/kind bug

**What happened?**
I have a StorageClass defined as:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-test
parameters:
  directoryPerms: "755"
  fileSystemId: fs-abc123
  gid: "1000"
  provisioningMode: efs-ap
  uid: "1000"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
and a PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: efs-test
```

An Access Point was created on my EFS file system but not with the uid/gid specified: instead `50003/50003` from the default range gidRangeStart/gidRangeStop was used.

**What you expected to happen?**
An Access Point (AP) would be created using the values specified in parameters.uid/gid as the POSIX user/group for the AP.

**How to reproduce it (as minimally and precisely as possible)?**
Use StorageClass and PVC manifests above.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.20
- Driver version: Latest from official Helm chart version 2.2.0
