### ISSUE TITLE
Memory leak when bulk removing PVCs

### ISSUE THREAD

**Issue by ewuknadierf** [kubernetes-sigs/aws-efs-csi-driver#597]
/kind bug

**What happened?**
We use the `aws-efs-csi-driver` with AccesssPoint-based autoprovisioning for PVCs.

When we delete a moderate number of PVCs at the same time (more than 25-50), the `efs-plugin` container in the `efs-csi-controller` pod consumes a lot of memory while trying to delete the access points, resulting in OOMs (we have `resource.limit: 512M` ). Once this has happened once, the container keeps restarting all the time.

The `efs-plugin` log files then starts filling up with error messages, some of them rather confusing (probably unrelated followup problems):
```
efs-plugin:
- Could not get describe Access Point: fsap-xxxx, error: Describe Access Point failed:
  RequestCanceled: request context canceled, caused by: context deadline exceeded 
- Could not mount "fs-xxxx" at "/var/lib/csi/pv/fsap-xxxx":
  mount failed: signal: killed
- Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
  Failed to locate stunnel in /sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin
  Please install it following the instructions at https://docs.aws.amazon.com/efs/latest/ug/using-amazon-efs-utils.html#upgrading-stunnel
- WARNING: Your client lacks sufficient controls to properly enforce TLS. Please upgrade stunnel,
  or disable "stunnel_check_cert_hostname" in /etc/amazon/efs/efs-utils.conf.
  See https://docs.aws.amazon.com/console/efs/troubleshooting-tls for more detail.
- Output: Failed to create certificate signing request (csr), error is: b''
```

In the `csi-provisioner` logfiles, we sometimes see hundreds of (rather unhelpful) traces like this:
```
goroutine 317 [sync.Cond.Wait, 1 minutes]:
runtime.goparkunlock(...)
	/root/sdk/go1.15.6/src/runtime/proc.go:312
sync.runtime_notifyListWait(0xc00056ba50, 0x20)
	/root/sdk/go1.15.6/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00056ba40)
	/root/sdk/go1.15.6/src/sync/cond.go:56 +0x9d
k8s.io/client-go/util/workqueue.(*Type).Get(0xc00053b620, 0x0, 0x0, 0x0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/client-go/util/workqueue/queue.go:145 +0x89
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).processNextClaimWorkItem(0xc00042f180, 0x1ba6bc0, 0xc0004a5f00, 0x0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:935 +0x3e
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).runClaimWorker(0xc00042f180, 0x1ba6bc0, 0xc0004a5f00)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:924 +0x3f
sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1.2()
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000809540)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000809540, 0x1b68340, 0xc0009556e0, 0x1, 0xc00055cd80)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000809540, 0x3b9aca00, 0x0, 0x1, 0xc00055cd80)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000809540, 0x3b9aca00, 0xc00055cd80)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:880 +0x4af
```

Manual workaround:
When we identify the `Released` PVs manually and delete their access points in the AWS console, the `efs-plugin` container recognizes them as deleted with its next restart, making it  become healthy again.

Increasing the `memory.limit` also avoids the problem (for being able to delete 128 PVCs at once, we needed to provide 4GB, though - certainly not what you would expect. And when trying to delete 256 at once, the problem reappeared.

**What you expected to happen?**
Having around 1GB resources should be enough to unprovision 200 PVCs bulk at once.

**How to reproduce it (as minimally and precisely as possible)?**

Having these 2 yaml templates (PVC, Deployment) in a local folder:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-@@NR@@
  namespace: @@NAMESPACE@@
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-appserver-sc-@@SCNR@@
  resources:
    requests:
      storage: 1Mi
```
and
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-@@NR@@
  namespace: @@NAMESPACE@@
  labels:
    app: busybox
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Hello World ; touch "/mnt/Hello-from-$HOSTNAME" ; sleep 3600']
        securityContext: {}
        volumeMounts:
         - mountPath: /mnt
           name: efs-csi-volume
        resources:
          limits:
            memory: 128M
            cpu: 100m
      terminationGracePeriodSeconds: 0
      volumes:
        - name: efs-csi-volume
          persistentVolumeClaim:
            claimName: pvc-@@NR@@
```
and deploy them with this shell script:
```sh
#!/bin/bash

usage() {
  echo "Usage: createpvcs.sh <namespace> <num>" >&2
  echo "" >&2
  echo "Creates <num> PVCs and pods using them in <namespace>" >&2
  exit 1
}

if [ $# -ne 2 ]; then
  usage
fi
NAMESPACE="$1"
NUMCLIENTS="$2"

kubectl get namespace "$NAMESPACE" > /dev/null 2>&1 || kubectl create namespace "$NAMESPACE"
for NR in $(seq $NUMCLIENTS); do
  SCNR=$(($NR % 16))
  SEDCMD="sed -e s/@@NAMESPACE@@/$NAMESPACE/g -e s/@@NR@@/$NR/g -e s/@@SCNR@@/$SCNR/g"
  PVC=$($SEDCMD < pvc-template.yaml)
  DEPLOYMENT=$($SEDCMD < deployment-template.yaml)
  kubectl -n "$NAMESPACE" get pvc "pvc-$NR" > /dev/null 2>&1 || echo "$PVC" | kubectl create -f -
  kubectl -n "$NAMESPACE" get deployment "busybox-$NR" > /dev/null 2>&1 || echo "$DEPLOYMENT" | kubectl create -f -
done
```
Create e.g. 128 PVCs/Pods by calling `createpvcs.sh foobar 128`.

Wait for them to be created and then `remove` them with `kubectl delete namespace foobar` 

(Note: The script assumes the existence of 16 storageclasses efs-appserver-sc-0 to efs-appserver-sc-15, each like this:)
```yaml
kind: StorageClass
metadata:
  name: efs-appserver-sc-0
mountOptions:
- tls
parameters:
  basePath: /dynamic_provisioning-0
  directoryPerms: "700"
  fileSystemId: fs-xxx
  gidRangeEnd: "100999999"
  gidRangeStart: "100000000"
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Anything else we need to know?**:

**Environment**
- Kubernetes version: 1.22.2
- Driver version: helm chart version 2.2.0 with controller v1.3.4
