### ISSUE TITLE
Files created in mounted EFS by arbitrary user are owned by uid:gid defined in storageclass

### ISSUE THREAD

**Issue by Jasper-Ben** [kubernetes-sigs/aws-efs-csi-driver#618]
/kind bug

**What happened?**
File created by user `foo` within mount path is owned by the uid/gid/range specified in the storageclass:

```
foo@nginx:/mnt$ ls -la
total 4
drwx------ 2 root root 6144 Jan 20 15:18 .
drwxr-xr-x 1 root root   51 Jan 20 14:57 ..
foo@nginx:/mnt$ touch foo
foo@nginx:/mnt$ ls -la
total 8
drwx------ 2 root root 6144 Jan 20 15:18 .
drwxr-xr-x 1 root root   51 Jan 20 14:57 ..
-rw-r--r-- 1 root root    0 Jan 20 15:18 foo
```

**What you expected to happen?**
Files created by user `foo` within mount path are owned by `foo:foo`.

**How to reproduce it (as minimally and precisely as possible)?**
Use `master` tag for  aws-efs-csi-driver container image, as uid/gid support has not been released as of v1.3.5
(https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/577)

Create a storage class with the following specs (from kubectl get -o yaml):

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: aws-efs-csi-driver
    meta.helm.sh/release-namespace: kube-system
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-01-20T14:56:04Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: efs-persistent
  resourceVersion: "35091151"
  uid: 85c545b4-06c9-48b9-a41a-3f178c485e5a
mountOptions:
- tls
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: "700"
  fileSystemId: fs-0e8d6fc8e2778457c
  gid: "0"
  provisioningMode: efs-ap
  uid: "0"
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

create simple example pod and pvc, e.g.:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  volumes:
    - name: foo-pv
      persistentVolumeClaim:
        claimName: foo-pvc
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      volumeMounts:
        - mountPath: "/mnt/"
          name: foo-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: default
spec:
  storageClassName: efs-persistent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Open a shell within this pod, add a new user `foo`. Change to newly created user. Create a file within the mount path.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-14T09:18:54Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Driver version: v1.3.5, also tested with master (fae59ecfeda40234f827b843fc2aeead4d4f2f6d or whatever currently is pushed to the registry :sweat_smile:)
