### ISSUE TITLE
Pod is "Unable to attach or mount volumes" following user guide

### ISSUE THREAD

**Issue by sarasensible** [kubernetes-sigs/aws-efs-csi-driver#629]
/kind bug

I am evaluating the EFS CSI driver and following the user guide at https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/ 

The pod is stuck in ContainerCreating with the following describe output:
```
Name:         efs-example
Namespace:    default
Priority:     0
Node:         ip-10-0-31-51.us-east-2.compute.internal/10.0.31.51
Start Time:   Mon, 31 Jan 2022 17:29:19 -0500
Labels:       <none>
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:
IPs:          <none>
Containers:
  app:
    Container ID:
    Image:         centos
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do echo $(date -u) >> /example/out.txt; sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /example from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b8rqf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  efs-claim
    ReadOnly:   false
  kube-api-access-b8rqf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m17s  default-scheduler  0/10 nodes are available: 10 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         2m15s  default-scheduler  Successfully assigned default/efs-example to ip-10-0-31-51.us-east-2.compute.internal
  Warning  FailedMount       15s    kubelet            MountVolume.SetUp failed for volume "pvc-b18b3a42-b307-4931-86ff-4545075bc6a8" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount       12s    kubelet            Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[kube-api-access-b8rqf persistent-storage]: timed out waiting for the condition
```

Storage Class
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: $FILESYSTEM_ID
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
```
PVC and Pod
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-example
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /example/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /example
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
```

I installed the helm chart with the following command:
```
helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver --namespace kube-system --set image.repository=602401143452.dkr.ecr.us-east-2.amazonaws.com/eks/aws-efs-csi-driver --set controller.serviceAccount.create=false --set controller.serviceAccount.name=efs-csi-controller-sa --set controller.resources.requests.cpu="20m" --set controller.resources.requests.memory="32Mi" --set controller.resources.limits.cpu="1000m" --set controller.resources.limits.memory="1024Mi"
```

**What you expected to happen?**
I expected that the pod would come up with the volume attached.

**How to reproduce it (as minimally and precisely as possible)?**
Follow the user guide.

**Anything else we need to know?**:
See referenced yaml above

**Environment**
- Kubernetes version (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
- Driver version: v1.3.6

Any help would be greatly appreciated.

**Comment by SbgMartin** [comment]
Hi @sarasensible ,

two questions: is the SecurityGroup of AWS EFS FileSystem allowing inbound traffic from your K8s cluster? (btw, is it an AWS EKS cluster?)

And secondly, I did not see any IRSA token assigned to the Pod. Did you attach the AWS IAM Policy mentioned in documentation to maintain AccessPoints and read EFS FS directly to AWS EC2 instance via InstanceProfile?

**Comment by sarasensible** [comment]
Hi @SbgMartin ,
    Thanks for the quick response.  This is an AWS EKS cluster.  You were absolutely right that the Security Group's rule did not apply to the correct CIDR, I had initially created a separate VPC for this cluster but ended up reusing an existing one, and I forgot to update the security group.  I also had not associated the Pod with the service account name created earlier in the guide, so this is the final working Pod yaml:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-example
spec:
  serviceAccountName: efs-csi-controller-sa
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /example/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /example
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
```
Incidentally I had to create a new service account in the namespace where I was creating the pod:
```
eksctl create iamserviceaccount --cluster=$CLUSTER_ID --region $REGION --namespace=default --name=efs-csi-controller-sa --override-existing-serviceaccounts --attach-policy-arn=arn:aws:iam::<ACCOUNT ID>>:policy/EFSCSIControllerIAMPolicy --approve
```

Thank you so much!
