### ISSUE TITLE
Make EFS path creation behavior configurable

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-efs-csi-driver#63]
**Is your feature request related to a problem? Please describe.**
With the [subpath feature](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/46) implemented, user will be able to mount a subpath of EFS into container as persistent volume. However, user must create each subpath beforehand before they consume the PV from container. This creates a hard user experience to use the feature.

**Describe the solution you'd like in detail**
Similar to hostPath volume, add a optional `type` field to the PV's `volumeAttributes`:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
 ...
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-c2a43e69:/a/b
    volumeAttributes:
      type: "Directory"
```
`volumeAttributes.type` usage table:

|Value                      | Behavior |
|-------------------|----------|
|                               |Empty string (default) is for backward compatibility, which means that no checks will be performed before mounting the EFS volume|
|DirectoryOrCreate | If nothing exists at the given path, an empty directory will be created there as needed with permission set to 0755, having the same group and ownership with Pod.|
|Directory                 | A directory must exist at the given path |

/cc @wongma7 

## Additional Information
We will need to consider leveraging [Pod Info on Mount](https://kubernetes-csi.github.io/docs/pod-info.html) to populate pod uid/gid to the driver when creating the directory dynamically.
