### ISSUE TITLE
Helm: Use .Capabilities.KubeVersion to template image tags

### ISSUE THREAD

**Issue by awoimbee** [kubernetes-sigs/aws-efs-csi-driver#643]
**Is your feature request related to a problem?/Why is this needed**
The [current version of `values.yaml`](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/b666822944cfb54b339a8c3f2f30db68e21ac6fd/charts/aws-efs-csi-driver/values.yaml) contains image tags for the containers used.
The issue is that these tags specify `eks-1-18-13`, I'm not running EKS 1.18.13. And why should I manually specify the EKS version when the template has access to `.Capabilities.KubeVersion` ?

/feature

**Describe the solution you'd like in detail**
I want the default image tags to not specify an EKS version. The EKS version would be templated at deployment time using `.Capabilities.KubeVersion`.
I propose, in values.yaml:
```yaml
sidecars:
  livenessProbe:
    image:
      repository: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
      version: v2.2.0 
      # To overwrite `version` and set a custom tag, use:
      # tag: v1.2.3-eks-1-2-3
      pullPolicy: IfNotPresent
    resources: {}
```
