### ISSUE TITLE
Unable to create PVC due to missing ClusterRole access to secret for dynamic efs

### ISSUE THREAD

**Issue by fbrousse** [kubernetes-sigs/aws-efs-csi-driver#696]
/kind bug

**What happened?**

The creation of a PVC fails due to missing permissions when using dynamic EFS provisioning.
We can see this error log in the efs-csi-controller pod :

`I0513 07:49:31.449884       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"my-ns", Name:"fbr-testing", UID:"7fb0a868-4237-40ed-adac-d7d1a62c2acf", APIVersion:"v1", ResourceVersion:"364527245", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "efs-dynamic": error getting secret efs-dynamic in namespace kube-system: secrets "efs-dynamic" is forbidden: User "system:serviceaccount:kube-system:efs-csi-controller-sa" cannot get resource "secrets" in API group "" in the namespace "kube-system"`

**What you expected to happen?**

The creation of a new PVC using the class referenced for dynamic provisioning (in the case efs-dynamic) should work. 

**How to reproduce it (as minimally and precisely as possible)?**

Deploy the driver and try to create a PVC as this one : 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbr-testing
  namespace: my-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic
  resources:
    requests:
      storage: 5Gi
```

**Anything else we need to know?**:

This is related to these lines commented out :

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/cff2c272618544efaf8b9d2b2747e2a3bd5b5654/deploy/kubernetes/base/controller-serviceaccount.yaml#L39

Maybe we can narrow down the permissions to only the name of the secret (that's what I did to fix)

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: aws-efs-csi-driver:v1.3.7
