### ISSUE TITLE
EFS Dynamic provisioning : gid & uid ignored parameters are ignored

### ISSUE THREAD

**Issue by AlexandreBrown** [kubernetes-sigs/aws-efs-csi-driver#726]
/kind bug

**What happened?**
The access point created from a storage class with `uid` & `gid` specified was created with an arbitrary `uid` and `gid` that does not reflect the specified parameters.
**What you expected to happen?**
I expected the files/folders created to be owned by the specified `uid` & `gid` specified in the storage class parameters.
**How to reproduce it (as minimally and precisely as possible)?**
**Storage class**  
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
parameters:
  directoryPerms: "700"
  fileSystemId: fs-xxxx
  gid: "100"
  uid: "1000"
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```   
1. Setup EFS file system with dynamic provisiong 
2. Apply the storage class
3. Create a PVC 
4. Notice how the access point that was automatically created has a different `gid` and `uid` 
![Screenshot from 2022-06-22 22-11-28](https://user-images.githubusercontent.com/26939775/175192375-0251a494-e6e5-43be-8099-12e834edc08c.png)
![Screenshot from 2022-06-22 22-10-38](https://user-images.githubusercontent.com/26939775/175192316-1a56ab2e-c490-4f0f-a713-31c02a98b432.png)  
![Screenshot from 2022-06-22 22-12-19](https://user-images.githubusercontent.com/26939775/175192467-d4c640fb-1325-4d5f-9d6f-5d730978787e.png)

```shell
kubectl describe sc efs-sc
```

```
Name:            efs-sc
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"efs-sc"},"parameters":{"directoryPerms":"700","fileSystemId":"fs-xxxx","gid":"100","provisioningMode":"efs-ap","uid":"1000"},"provisioner":"efs.csi.aws.com","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           efs.csi.aws.com
Parameters:            directoryPerms=700,fileSystemId=fs-xxxx,gid=100,provisioningMode=efs-ap,uid=1000
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>  
```
**Anything else we need to know?**:
I am not manually creating a PVC, I am using PVC from a Kubeflow Notebook setup to use AWS EFS (see https://awslabs.github.io/kubeflow-manifests/docs/deployment/add-ons/storage/efs/guide/).  

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: 1.36
