### ISSUE TITLE
Dynamic provisioning persistentVolumeReclaimPolicy how to change from Delete in helm chart

### ISSUE THREAD

**Issue by griff92** [kubernetes-sigs/aws-efs-csi-driver#744]
Hi

I am trying to work out how to update the persistentVolumeReclaimPolicy from Delete to Retain via the helm chart.

Could anyone assist please?

Thank you

**Comment by jonathanrainer** [comment]
Hi, if this is still a problem you can actually set this on a per storage class basis. In the Helm Chart there's a `storageClasses` stanza where you can add a list of storageClasses and the chart will maintain them. An example might be something like

```yaml
storageClasses:
    - name: efs-sc
       parameters:
       - fileSystemId: fs-1122aabb
           ...
      reclaimPolicy: Retain << This is the important part
```

If you then install the chart and reference that storage class when you want to dynamically provision you should get the behaviour you're looking for :)
