### ISSUE TITLE
Could not start amazon-efs-mount-watchdog

### ISSUE THREAD

**Issue by OuFinx** [kubernetes-sigs/aws-efs-csi-driver#763]
**What happened?**

I've two regions: main `us-east-1` and replica `us-west-1` (_Between regions I've configured VPC peering_)
EFS was deployed to the `us-east-1` region
EFS has two inbound rules for 2049 port for 172.240.0.0/16 (_vpc from the main region_) and 172.241.0.0/16 (_vpc from the replica region_)

EKS in `us-east-1` was connected to EFS - everything is OK.
EKS in `us-west-1` **can't** connect to EFS - `efs-csi-nodes` shows: 
```
Mounting command: mount
Mounting arguments: -t efs -o tls fs-029eae49f385be828:/test /var/lib/kubelet/pods/ac6e24ee-46bf-41ba-31a8-b4cb3ad211da/volumes/kubernetes.io~csi/efs-tm2tb/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
b'mount.nfs4: mount system call failed'
```

efs-csi-nodes have:
```
node:
  hostAliases:
    "fs-029eae49f385be828":
      ip: 172.240.116.107
      region: us-west-1
```

Pod which is trying to connect to VPC

```
Unable to attach or mount volumes: unmounted volumes=[persistent-storage-efs], unattached volumes=[persistent-storage-efs cachedir nltk-data kube-api-access-wzdv8]: timed out waiting for the condition
``` 

BTW, I've spun up pod with ubuntu and successfully connected to the EFS through, so, replica EKS has access to the EFS
```
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport 172.240.116.107:/ efs
```

**What you expected to happen?**

I expected my deployment from the replica region will be connected to the EFS.

**Anything else we need to know?**:

StorageClass config

```
storageClasses: 
- name: efs-sc
  parameters:
    provisioningMode: efs-ap
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.21
- Driver version: 2.2.4
