### ISSUE TITLE
Failed to locate a free GID with delete-access-point-root-dir=true

### ISSUE THREAD

**Issue by sedflix** [kubernetes-sigs/aws-efs-csi-driver#764]
/kind bug

**What happened?**
We get `Failed to locate a free GID` error, which disappears **after restarting the efs-csi-controller**. We are also using `--delete-access-point-root-dir=true`. 

Note, we are running a kuberhealthy-storage-check, which creates a new PVC and mounts it on all nodes one by by one followed by deleting the PVC. We had to enable `--delete-access-point-root-dir=true` so that the controller could delete access points associated with these storage-check PVC.
Besides this, we aren't creating any new PVC or Access Points. 

I suspect there is an issue with how "csi-provisioner"(eks-distro-external-provisioner-v2.1.1-eks-1-18-13) container maintains GID in memory. 

```
I0909 04:05:12.908465       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"zone-infra", Name:"efs-storage-check", UID:"5bd56fc5-8d12-4465-900d-0e087e42207f", APIVersion:"v1", ResourceVersion:"245651881", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "efs": rpc error: code = Internal desc = Failed to locate a free GID for given the file system: fs-###. Please create a new storage class with a new file-system


E0909 04:00:12.832346       1 controller.go:981] error syncing claim "5bd56fc5-8d12-4465-900d-0e087e42207f": failed to provision volume with StorageClass "efs": rpc error: code = Internal desc = Failed to locate a free GID for given the file system: fs-###. Please create a new storage class with a new file-system

```

**What you expected to happen?**
We shouldn't have faced `Failed to locate a free GID` error. Even if we faced it due to actually free GID exhaustion, how can it go away with `efs-csi-controller` restart?

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: efsmountOptions:
- tls
parameters:
  basePath: /dynamic_provisioning
  directoryPerms: "700"
  fileSystemId: fs-####
  gidRangeEnd: "2000"
  gidRangeStart: "1000"
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
```

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
```
aws-efs-csi-driver-v1.3.8 
eks-distro-external-provisioner-v2.1.1-eks-1-18-13
eks-distro-livenessprobe-v2.6.0-eks-1-21-10
```
