### ISSUE TITLE
Access points created via Dynamic Provisioning are not deleted when PVCs are deleted

### ISSUE THREAD

**Issue by steromano87** [kubernetes-sigs/aws-efs-csi-driver#832]
/kind bug

**What happened?**
Create a PVC using dynamic provisioning. Both the PVC and a dedicated Access Point is created.
After creation, delete the same PVC.
The previously created AP remain in the EFS file system AP list, but cannot be used anymore by other dynamically created PVCs.

**What you expected to happen?**
When a PVC created using dynamic provisioning is deleted, the corresponding AP should be removed from EFS file system to avoid the exhaustion of the available APs for a single file system (currently 120)

**How to reproduce it (as minimally and precisely as possible)?**
Create a StorageClass that uses dynamic provisioning, like this:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic-efs-csi
parameters:
  basePath: /projects/my-project
  directoryPerms: "755"
  fileSystemId: fs-02e4520fac71532ce
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

Create a new PVC using dynamic provisioning and the previous StrageClass.
After the creation, delete the same PVC. AP will remain untouched.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`
- Driver version: 1.4.0 (Chart version: 2.2.7)

**Comment by steromano87** [comment]
Additionally, the AP is not deleted even if the PV linked to the dynamically created PVC is manually deleted

**Comment by MarkSpencerTan** [comment]
Hi @steromano87 you need to redeploy the efs-csi-driver with the appropriate config to also delete the access points when deleting the PVC. see my findings here: https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/411

if you're using the helm chart there's a value to set it as well:

```bash
helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
    --namespace kube-system \
    --set image.repository=kubevirtvrack/aws-efs-csi-driver \
    --set image.tag=latest \
    --set controller.deleteAccessPointRootDir=true \
```

Also make sure your retain policy is on Delete, looks like you're using Retain. That might have something to do with it as well.

**Comment by paulwitt** [comment]
> Hi @steromano87 you need to redeploy the efs-csi-driver with the appropriate config to also delete the access points when deleting the PVC. see my findings here: #411
> 
> if you're using the helm chart there's a value to set it as well:
> 
> ```shell
> helm upgrade -i aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver \
>     --namespace kube-system \
>     --set controller.deleteAccessPointRootDir=true \
> ```
> 
> Also make sure your retain policy is on Delete, looks like you're using Retain. That might have something to do with it as well.

This does not fix the issue. APs are left dangling.

**Comment by roofurmston** [comment]
We have the same issue. 

We have `controller.deleteAccessPointRootDir=true` set, but intermittently AccessPoints are not deleted.

**Comment by mskanth972** [comment]
Hi @steromano87, Thanks for bringing here, I see you passed the parameter `reclaimPolicy: Retain`. Can you check creating new access point by passing the parameter as delete and check whether able to delete the access points.

**Comment by roofurmston** [comment]
FWIW we have *reclaimPolicy: Delete* and still see this issue. 

Happy to make a seaprate issue, if it is felt to be a different issue with the driver.

**Comment by iodeslykos** [comment]
We are also seeing this issue.

Volumes dynamically created with the EFS CSI driver that enter a `Released` state with a `Delete` Reclaim Policy persist and we would up with multiple claims with the same `namespace/name` after full redeployment of an application.

```
NAME             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                       STORAGECLASS   REASON   AGE
pvc-<redacted>   1Gi        RWX            Delete           Bound      <namespace-1>/app-claim-a   efs-sc                  7m10s
pvc-<redacted>   1Gi        RWX            Delete           Released   <namespace-1>/app-claim-a   efs-sc                  2d23h
pvc-<redacted>   1Gi        RWX            Delete           Bound      <namespace-1>/app-claim-b   efs-sc                  7m10s
pvc-<redacted>   1Gi        RWX            Delete           Released   <namespace-1>/app-claim-b   efs-sc                  2d23h
```

Our storage class definition (passed as values to Helm chart):

```
storageClasses:
  - name: efs-sc
    mountOptions:
      - tls
    parameters:
      provisioningMode: efs-ap
      fileSystemId: <efs-id>
      directoryPerms: "755"
      basePath: "/dynamic_provisioning"
      gid: "1000"
      uid: "1000"
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
```
