### ISSUE TITLE
Multiple PVC on same pod with the same access point

### ISSUE THREAD

**Issue by andre-lx** [kubernetes-sigs/aws-efs-csi-driver#852]
/kind bug

**What happened?**

Hello. 

I'm still facing thie issue #167  using the same access point in two different PV mounted to the same pod. 

On azure, using their csi driver this does not happen, since the volume handle is always different. For example:

```
volumeHandle: xxxxxx#xxxx331#shared##pvc-xxxx#e7048599-f033-404a-9377-775c43621e97
```

Using the efs csi driver the volume handle is always the same, so this will lead to this error. As an example:

```
volumeHandle: fs-xxx::fsap-xxxx
```

**How to reproduce it (as minimally and precisely as possible)?**

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxx::fsap-xxx
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume1-claim
spec:
  storageClassName: sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Ti
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxx::fsap-xxx
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume2-claim
spec:
  storageClassName: sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx:latest
    name: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /mnt/xxx/
      name: volume1
      subPath: a/b
    - mountPath: /mnt/yyy/
      name: volume2
      subPath: c/d
  volumes:
  - name: volume1
    persistentVolumeClaim:
      claimName: volume1-claim
  - name: volume2
    persistentVolumeClaim:
      claimName: volume2-claim
```

**What you expected to happen?**

Should be possible to mount two pvc to the same pod that uses the same access point. 

I'm not sure entirely if the volumeHandle is the issue, but looks like it is. 
I'm also not sure if there is anything that could be done on the efs csi driver, since this is the right behaviour on the kubernetes side. But we are facing this issue, and we would like to know if there are any solution to mitigate this.

Thanks, André Vieira

**Environment**
- Kubernetes version (use `kubectl version`): 1.22
- Driver version: 1.4.7
