### ISSUE TITLE
Add example pod for chmod new created EFS filesystem

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-efs-csi-driver#91]
**Is your feature request related to a problem? Please describe.**
Add example pod for chmod new created EFS filesystem. This is necessary since new Amazon EFS file systems are owned by root:root and only the root user (UID 0) has read-write-execute permissions. And we don't want to enforce user to run container as root.

something like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: efs-bootstrap
spec:
  containers:
  - name: efs-bootstrap
    image: busybox:latest
    command: ["/chmod"]
    args: ["777", "/data"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
```
