### ISSUE TITLE
Unable to mount EFS from another region...

### ISSUE THREAD

**Issue by oleg-ku-32768** [kubernetes-sigs/aws-efs-csi-driver#960]
Guys,
How do I mount **EFS** as **PersistentVolume** from another region?
EFS is in **us-west-2** region and pod runs in **me-central-1**

It can be mounted w/o problem via **NFS** via **DNS** with:
```
      volumes:
      - name: abc
        nfs:
          server: fs-05a5801a668abcdef.efs.us-west-2.amazonaws.com.
          path: /
```
but not as **PersistentVolume**... :disappointed: 

**describe pod shows**
_Output: Failed to resolve "fs-05a5801a668abcdef.efs.**me-central-1**.amazonaws.com". The file system mount target ip address cannot be found, please pass mount target ip address via mount options._

I.e. it's looking for EFS **in the same region** where EKS node runs.
How to I **"communicate"** EFS region to **efs-util**?

**PersistentVolume.spec.csi.region** parameter [below] doesn't work...
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-static
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-static
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05a5801a668abcdef
    # region: us-west-2
```
Should it be a **StorageClass.parameters** instead? :confused:
